// resources/js/Pages/Editor/Dashboard.tsx
import {Head} from "@inertiajs/react";
import {PageProps} from "@/types";
import Admin from "@/Layouts/Admin";
import TableHeader from "@/Components/Tables/TableHeader";
import Table from "@/Components/Tables/Table";
import TableBody from "@/Components/Tables/TableBody";
import TableHead from "@/Components/Tables/TableHead";
import {Header3} from "@/Components/Typography/Headers";
import NoAssignments from "@/Components/EmptyStates/NoAssignments";

const cells = {
    assignable: 'Belongs to',
    type: 'Type',
    status: 'Status',
    created_at: 'Created',
}

const tableActions = {
    view: true,
    edit: false,
}

export default function EditorDashboard({ assignments, auth, drafts }: PageProps) {
    return (
        <>
            <Head title="Editor Dashboard"/>

            <Admin user={auth.user}>
                <div className="flex-1 px-4 py-8 sm:px-6 lg:px-8">
                    <header>
                        <div className="mx-auto">
                            <h2 className="text-xl font-bold leading-tight tracking-tight text-gray-900">
                                Welcome, {auth.user.name.split(' ')[0]}
                            </h2>
                        </div>
                    </header>

                    {assignments.length ? (
                        <>
                            <TableHeader header="Assignments"/>
                            <Table className="mt-2">
                                <TableHead cells={cells} actions={true}/>
                                <TableBody
                                    cells={cells}
                                    rows={assignments}
                                    routeType="editor.assignments"
                                    actions={tableActions}
                                />
                            </Table>
                        </>
                    ) : <NoAssignments/>}

                    {drafts.length ? (
                        <div className="mt-6">
                            <Header3>
                                My Drafts
                            </Header3>
                            <div className="mt-4">
                                {/*DraftList*/}
                            </div>
                        </div>
                    ) : null}
                </div>
            </Admin>
        </>
    );
}

// resources/js/Pages/Editor/Dashboard.vue
<script setup>
import { computed } from 'vue';
import AdminLayout from '@/Layouts/Admin.vue';
import { Head, Link } from '@inertiajs/vue3';
import Badge from '@/Components/Badge.vue';
import TableHeader from '@/Components/Tables/TableHeader.vue';
import Table from '@/Components/Tables/Table.vue';
import TableHead from '@/Components/Tables/TableHead.vue';
import TableBody from '@/Components/Tables/TableBody.vue';
import DraftList from '@/Components/Drafts/DraftList.vue';
import NoAssignments from '@/Components/EmptyStates/EditorDashboard.vue';
import Header3 from '@/Components/Headers/Header3.vue';

defineProps({
    assignments: Array,
    drafts: Array
});

const cells = {
    assignable: 'Belongs to',
    type: 'Type',
    status: 'Status',
    created_at: 'Created'
}

const tableActions = {
    view: true,
    edit: false
}
</script>

<template>

    <Head title="Editor Dashboard" />

    <AdminLayout>
        <div class="flex-1 px-4 py-8 sm:px-6 lg:px-8">
            <header>
                <div class="mx-auto">
                    <h2 class="text-xl font-bold leading-tight tracking-tight text-gray-900">Welcome, {{ $page.props.auth.user.name.split(' ')[0] }}</h2>
                </div>
            </header>

            <div v-if="assignments.length" class="mt-6">
                <TableHeader header="Assignments" />
                <Table class="mt-2">
                    <TableHead :cells="cells" :actions="true" />
                    <TableBody :cells="cells" :rows="assignments" routeType="editor.assignments" :actions="tableActions" />
                </Table>
            </div>

            <div v-if="drafts.length" class="mt-6">
                <Header3> My Drafts </Header3>
                <div class="mt-4">
                    <DraftList :drafts="drafts" />
                </div>
            </div>

            <NoAssignments v-if="! assignments.length && ! drafts.length" />
        </div>
    </AdminLayout>
</template>
