// resources/js/Components/DangerButton.vue
<script setup>
import { Link } from '@inertiajs/inertia-vue3';

defineProps({
    type: {
        type: String,
        default: 'submit',
    }
});

const classes = "inline-flex items-center justify-center rounded-md border border-transparent bg-red-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-red-700 focus:ring focus:ring-red-500 focus:ring-opacity-40 sm:w-auto";
</script>

<template>
    <button :type="type" :class="classes">
        <slot />
    </button>
</template>

// resources/js/Components/Buttons/DangerButton.tsx
import {type ButtonHTMLAttributes, type ReactElement} from 'react'

export default function DangerButton({
  className = '',
  disabled,
  children,
  ...props
}: ButtonHTMLAttributes<HTMLButtonElement>): ReactElement {
    return (
        <button
            {...props}
            className={
                `inline-flex items-center justify-center rounded-md border border-transparent bg-red-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-red-700 focus:ring focus:ring-red-500 focus:ring-opacity-40 sm:w-auto transition ease-in-out duration-150 ${
                    disabled && 'opacity-25'
                } ` + className
            }
            disabled={disabled}
        >
            {children}
        </button>
    )
}
