// resources/js/Components/Buttons/PrimaryButton.vue
<script setup>
import { Link } from '@inertiajs/vue3';

defineProps({
    as: String,
    href: String,
    type: {
        type: String,
        default: 'submit',
    }
});

const classes = "inline-flex items-center justify-center rounded-md border border-transparent bg-blue-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-blue-700 focus:ring focus:ring-blue-500 focus:ring-opacity-40 sm:w-auto";
</script>

<template>
    <Link :href="href" :class="classes" v-if="as === 'link'">
        <slot />
    </Link>
    <button :type="type" :class="classes" v-else>
        <slot />
    </button>
</template>

// resources/js/Components/Buttons/PrimaryButton.tsx
import { type ButtonHTMLAttributes, type ReactElement } from 'react'

export default function PrimaryButton ({
   className = '',
   disabled,
   children,
   ...props
}: ButtonHTMLAttributes<HTMLButtonElement>): ReactElement {
    return (
        <button
            {...props}
            className={
                `inline-flex items-center justify-center rounded-md border border-transparent bg-blue-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-blue-700 focus:ring focus:ring-blue-500 focus:ring-opacity-40 sm:w-auto transition ease-in-out duration-150 ${
                    disabled && 'opacity-25'
                } ` + className
            }
            disabled={disabled}
        >
            {children}
        </button>
    )
}
