// resources/js/Components/Notifications/Notification.tsx
import { Fragment, type ReactElement, useEffect, useState } from 'react'
import { Transition } from '@headlessui/react'
import { Link, usePage } from '@inertiajs/react'
import { CheckCircleIcon, XCircleIcon, XMarkIcon } from '@heroicons/react/24/solid'

export default function Notification (): ReactElement | null {
  const [showNotification, setShowNotification] = useState(true)
  let { notification } = usePage().props.flash

  useEffect(() => {
    const timer = setTimeout(() => {
      notification = null
      setShowNotification(false)
    }, 5000)
    return () => { clearTimeout(timer) }
  }, [])

  return showNotification && notification !== null ? (
    <div aria-live="assertive" className="pointer-events-none fixed inset-0 flex items-end px-6 py-6 sm:items-start sm:p-6">
      <div className="flex w-full flex-col items-center space-y-4 sm:items-end">
        <Transition
          show={showNotification && notification !== null}
          as={Fragment}
          enter="transform ease-out duration-300 transition"
          enterFrom="translate-y-2 opacity-0 sm:translate-y-0 sm:translate-x-2"
          enterTo="translate-y-0 opacity-100 sm:translate-x-0"
          leave="transition ease-in duration-100"
          leaveFrom="opacity-100"
          leaveTo="opacity-0"
        >
          <div className="pointer-events-auto w-full max-w-sm overflow-hidden rounded-lg bg-white shadow-lg ring-1 ring-black ring-opacity-5">
            <div className="p-4">
              <div className="flex items-start">
                <div className="flex-shrink-0">
                  {notification?.type === 'error' && <XCircleIcon className="h-6 w-6 text-red-400" aria-hidden="true"/>}
                  {notification?.type === 'success' && <CheckCircleIcon className="h-6 w-6 text-green-400" aria-hidden="true"/>}
                </div>
                <div className="ml-3 w-0 flex-1 pt-0.5">
                  <p className="text-sm font-medium text-gray-900">
                    {notification?.title}
                  </p>
                  <p className="mt-1 text-sm text-gray-500">
                    {notification?.message}
                  </p>
                  {notification?.actions !== false && (
                    <div className="mt-3 flex space-x-7">
                      {notification?.actions.view !== undefined && (
                        <Link
                          href={notification?.actions.view.href}
                          className="rounded-md bg-white text-sm text-blue-400 hover:text-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"
                        >
                          View
                        </Link>
                      )}
                    </div>
                  )}
                </div>
                <div className="ml-4 flex flex-shrink-0">
                  <button
                    type="button"
                    onClick={() => { setShowNotification(false) }}
                    className="inline-flex rounded-md bg-white text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"
                  >
                    <span className="sr-only">Close</span>
                    <XMarkIcon className="h-5 w-5" aria-hidden="true"/>
                  </button>
                </div>
              </div>
            </div>
          </div>
        </Transition>
      </div>
    </div>
  ) : null
}

// resources/js/Components/Notifications/Notification.vue
<script setup>
import { computed, ref, watch } from 'vue';
import { CheckCircleIcon, InboxIcon, XCircleIcon } from '@heroicons/vue/24/outline';
import { XMarkIcon } from '@heroicons/vue/20/solid';
import { Link, usePage } from '@inertiajs/vue3';

const show = ref(true);

const notification = computed(() => usePage().props.flash.notification);

watch(notification, async () => {
    show.value = true;
    setTimeout(() => usePage().props.flash.notification = null, 4000);
});
</script>

<template>
    <!-- Global notification live region, render this permanently at the end of the document -->
    <div aria-live="assertive" class="pointer-events-none fixed inset-0 flex items-end px-4 py-6 sm:items-start sm:p-6">
        <div class="flex w-full flex-col items-center space-y-4 sm:items-end">
            <!-- Notification panel, dynamically insert this into the live region when it needs to be displayed -->
            <transition enter-active-class="transform ease-out duration-300 transition"
                enter-from-class="translate-y-2 opacity-0 sm:translate-y-0 sm:translate-x-2"
                enter-to-class="translate-y-0 opacity-100 sm:translate-x-0"
                leave-active-class="transition ease-in duration-200" leave-from-class="opacity-100"
                leave-to-class="opacity-0">
                <div v-if="show && notification"
                    class="pointer-events-auto w-full max-w-sm overflow-hidden rounded-lg bg-white shadow-lg ring-1 ring-black ring-opacity-5">
                    <div class="p-4">
                        <div class="flex items-start">
                            <div class="flex-shrink-0">
                                <XCircleIcon v-if="notification.type === 'error'" class="h-6 w-6 text-red-400" aria-hidden="true" />
                                <CheckCircleIcon v-if="notification.type === 'success'" class="h-6 w-6 text-green-400" aria-hidden="true" />
                            </div>
                            <div class="ml-3 w-0 flex-1 pt-0.5">
                                <p class="text-sm font-medium text-gray-900">
                                    {{ notification.title }}
                                </p>
                                <p class="mt-1 text-sm text-gray-500">
                                    {{ notification.message }}
                                </p>
                                <div v-if="notification.actions" class="mt-3 flex space-x-7">
                                    <button v-if="notification.actions.undo" type="button"
                                        class="rounded-md bg-white text-sm font-medium text-blue-600 hover:text-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2">Undo</button>
                                    <Link v-if="notification.actions.view" :href="notification.actions.view.href"
                                        class="rounded-md bg-white text-sm font-medium text-blue-600 hover:text-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2">View</Link>
                                </div>
                            </div>
                            <div class="ml-4 flex flex-shrink-0">
                                <button type="button" @click="show = false"
                                    class="inline-flex rounded-md bg-white text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2">
                                    <span class="sr-only">Close</span>
                                    <XMarkIcon class="h-5 w-5" aria-hidden="true" />
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </transition>
        </div>
    </div>
</template>
