// resources/js/Pages/Editor/Content/Collections/Edit.tsx
import { type FormEventHandler, type ReactElement } from 'react'
import { Head, useForm } from '@inertiajs/react'
import Admin from '@/Layouts/Admin'
import Container from '@/Components/Container'
import { Header3 } from '@/Components/Typography/Headers'
import SecondaryButton from '@/Components/Buttons/SecondaryButton'
import PrimaryButton from '@/Components/Buttons/PrimaryButton'
import InputLabel from '@/Components/Forms/InputLabel'
import TextInput from '@/Components/Forms/TextInput'
import InputError from '@/Components/Forms/InputError'
import { type Collection, type PageProps } from '@/types'

export default function CollectionEdit ({ auth, collection }: PageProps<{ collection: Collection }>): ReactElement {
  const { data, setData, put, errors } = useForm<Collection>({
    ...collection
  })

  const submit: FormEventHandler = (e) => {
    e.preventDefault()

    put(route('editor.collections.update', [collection.id]))
  }

  return (
    <>
      <Head title={`Admin - Edit ${collection.name}`}/>

      <Admin user={auth.user}>
        <Container>
          <Header3>
            Edit Collection: {collection.name}
          </Header3>
          <div className="mt-4 bg-white shadow overflow-hidden sm:rounded-lg">
            <form onSubmit={submit} className="sm:divide-y sm:divide-gray-200">
              <div className="px-6 sm:grid sm:grid-cols-8 sm:gap-4 sm:items-start sm:py-4">
                <InputLabel label="Collection name" className="sm:mt-px sm:pt-2"/>
                <div className="mt-1 sm:mt-0 sm:col-span-7">
                  <TextInput
                    value={data.name}
                    className="mt-1 block w-full"
                    onChange={(e) => { setData('name', e.target.value) }}
                    isFocused
                  />
                  <InputError message={errors.name} className="mt-1"/>
                </div>
              </div>
              <div className="px-6 py-4 sm:border-t sm:border-gray-200">
                <div className="flex justify-end space-x-3">
                  <SecondaryButton href={route('editor.collections.show', [collection.id])}>
                    Cancel
                  </SecondaryButton>
                  <PrimaryButton type="submit">
                    Save
                  </PrimaryButton>
                </div>
              </div>
            </form>
          </div>
        </Container>
      </Admin>
    </>
  )
}

// resources/js/Pages/Admin/Collections/Edit.vue
<script setup>
import AdminLayout from '@/Layouts/Admin';
import { Head } from '@inertiajs/inertia-vue3';
import BreezeInput from '@/Components/Input';
import BreezeInputError from '@/Components/InputError';
import BreezeLabel from '@/Components/Label';
import PrimaryButton from '@/Components/PrimaryButton';
import SecondaryButton from '@/Components/SecondaryButton';
import { Inertia } from '@inertiajs/inertia';

const props = defineProps({
    collection: Object,
});

const submit = () => {
    Inertia.put(route('admin.collections.update', [props.collection.slug]), props.collection);
}
</script>

<template>
    <Head :title="`Admin - Edit ${collection.name}`" />

    <AdminLayout>
        <div class="w-full py-8 px-4 sm:px-6 lg:px-8">
            <h3 class="text-lg leading-6 font-medium text-gray-900 mt-2"> Edit Collection: {{ collection.name }} </h3>
            <div class="mt-4 bg-white shadow overflow-hidden sm:rounded-lg">
                <form @submit.prevent="submit" class="sm:divide-y sm:divide-gray-200">
                    <div class="px-6 sm:grid sm:grid-cols-5 sm:gap-4 sm:items-start sm:border-t sm:border-gray-200 sm:py-4">
                        <BreezeLabel for="name" value="Collection name" class="sm:mt-px sm:pt-2" />
                        <div class="mt-1 sm:mt-0 sm:col-span-4">
                            <BreezeInput type="text" v-model="collection.name" id="name" class="block w-full" />
                            <BreezeInputError class="mt-1" :message="collection.errors?.name" />
                        </div>
                    </div>
                    <div class="px-6 py-4 sm:border-t sm:border-gray-200">
                        <div class="flex justify-end">
                            <SecondaryButton :href="route('admin.collections.show', [collection.slug])" as="link">Cancel</SecondaryButton>
                            <PrimaryButton type="submit" class="ml-3">Save</PrimaryButton>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </AdminLayout>
</template>
