// resources/js/Pages/Editor/Content/Collections/Create.vue
<script setup>
import AdminLayout from '@/Layouts/Admin.vue';
import { Head, useForm } from '@inertiajs/vue3';
import BreezeInput from '@/Components/Input.vue';
import BreezeInputError from '@/Components/InputError.vue';
import BreezeLabel from '@/Components/Label.vue';
import PrimaryButton from '@/Components/Buttons/PrimaryButton.vue';
import SecondaryButton from '@/Components/Buttons/SecondaryButton.vue';
import Header3 from '@/Components/Headers/Header3.vue';

const collection = useForm({
    name: '',
});

const submit = () => {
    collection.post(route('editor.collections.store'));
}
</script>

<template>
    <Head title="Admin - Create Collection" />

    <AdminLayout>
        <div class="w-full py-8 px-4 sm:px-6 lg:px-8">
            <Header3> Create Collection </Header3>
            <div class="mt-4 bg-white shadow overflow-hidden sm:rounded-lg">
                <form @submit.prevent="submit" class="sm:divide-y sm:divide-gray-200">
                    <div class="px-6 sm:grid sm:grid-cols-5 sm:gap-4 sm:items-start sm:py-4">
                        <BreezeLabel for="name" value="Collection name" class="sm:mt-px sm:pt-2" />
                        <div class="mt-1 sm:mt-0 sm:col-span-4">
                            <BreezeInput type="text" v-model="collection.name" id="name" class="block w-full" />
                            <BreezeInputError class="mt-1" :message="collection.errors?.name" />
                        </div>
                    </div>
                    <div class="px-6 py-4 sm:border-t sm:border-gray-200">
                        <div class="flex justify-end">
                            <SecondaryButton :href="route('editor.collections.index')" as="link">Cancel</SecondaryButton>
                            <PrimaryButton type="submit" class="ml-3">Save</PrimaryButton>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </AdminLayout>
</template>

// resources/js/Pages/Editor/Media/Create.tsx
import { type ChangeEvent, type ReactElement } from 'react'
import { type PageProps } from '@/types'
import { Head, useForm } from '@inertiajs/react'
import Admin from '@/Layouts/Admin'
import Container from '@/Components/Container'
import { Header3 } from '@/Components/Typography/Headers'
import PrimaryButton from '@/Components/Buttons/PrimaryButton'
import InputLabel from '@/Components/Forms/InputLabel'
import TextInput from '@/Components/Forms/TextInput'
import InputError from '@/Components/Forms/InputError'
import FileInput from '@/Components/Forms/FileInput'

export default function MediaCreate ({ auth }: PageProps): ReactElement {
  const { data, setData, errors, processing, post } = useForm({
    name: '',
    file: {}
  })

  const handleFileChange = (e: ChangeEvent<HTMLInputElement>): void => {
    const { files } = e.target

    if (files !== null) {
      setData('file', files[0])
    }
  }

  const submit = (e): void => {
    e.preventDefault()

    post(route('editor.media.store'))
  }

  return (
    <>
      <Head title="Add Media"/>

      <Admin user={auth.user}>
        <Container>
          <div className="flex items-center justify-between flex-wrap sm:flex-nowrap">
            <Header3>
              Add Media
            </Header3>
            <PrimaryButton onClick={submit} disabled={processing}>
              Save
            </PrimaryButton>
          </div>

          <div className="mt-4 bg-white rounded-md shadow">
            <form className="sm:divide-y sm:divide-gray-200">
              <div className="px-6 sm:grid sm:grid-cols-8 sm:gap-4 sm:items-start sm:py-4">
                <InputLabel label="Name" className="sm:mt-px sm:pt-2"/>
                <div className="mt-1 sm:mt-0 sm:col-span-7">
                  <TextInput
                    value={data.name}
                    className="block w-full"
                    isFocused={true}
                    onChange={(e) => {
                      setData('name', e.target.value)
                    }}
                  />
                  <InputError message={errors.name}/>
                </div>
              </div>

              <div className="px-6 sm:grid sm:grid-cols-8 sm:gap-4 sm:items-start sm:py-4">
                <InputLabel label="Image" className="sm:mt-px sm:pt-2"/>
                <div className="mt-1 sm:mt-0 sm:col-span-7">
                  <FileInput
                    className="block w-full"
                    onChange={(e) => {
                      handleFileChange(e)
                    }}
                  />
                  <InputError message={errors.file}/>
                </div>
              </div>
            </form>
          </div>
        </Container>
      </Admin>
    </>
  )
}
