// resources/js/Pages/Editor/Content/Projects/Edit.tsx
import { type FormEventHandler, type ReactElement } from 'react'
import { Head, useForm } from '@inertiajs/react'
import Admin from '@/Layouts/Admin'
import Container from '@/Components/Container'
import { Header3 } from '@/Components/Typography/Headers'
import AddCoverImage from '@/Components/Forms/AddCoverImage'
import InputLabel from '@/Components/Forms/InputLabel'
import TextInput from '@/Components/Forms/TextInput'
import InputError from '@/Components/Forms/InputError'
import SecondaryButton from '@/Components/Buttons/SecondaryButton'
import PrimaryButton from '@/Components/Buttons/PrimaryButton'
import { type Collection, type PageProps, type Project } from '@/types'

export default function ProjectEdit ({ auth, collections, project }: PageProps<{
  collections: Collection[]
  project: Project
}>): ReactElement {
  const { data, setData, errors, put } = useForm({
    name: project.name,
    image: {}
  })

  const updateCover = (value: File): void => {
    setData('image', value)
  }

  const submit: FormEventHandler = (e) => {
    e.preventDefault()

    put(route('editor.projects.update'), [project.id])
  }

  return (
    <>
      <Head title={`Admin - Projects - Edit ${project.name}`}/>

      <Admin user={auth.user}>
        <Container>
          <Header3>
            Edit Project: {project.name}
          </Header3>
          <div className="mt-4 bg-white rounded-md shadow">
            <form onSubmit={submit} className="sm:divide-y sm:divide-gray-200">
              <div className="px-6 sm:grid sm:grid-cols-5 sm:gap-4 sm:items-start sm:py-4">
                <InputLabel label="Project name" className="sm:mt-px sm:pt-2"/>
                <div className="mt-1 sm:mt-0 sm:col-span-4">
                  <TextInput
                    value={data.name}
                    className="block w-full"
                    isFocused={true}
                    onChange={(e) => {
                      setData('name', e.target.value)
                    }}
                  />
                  <InputError message={errors.name}/>
                </div>
              </div>
              <AddCoverImage
                name={data.name}
                errorMessage={errors.image}
                imagePath={project.cover_image_path}
                imageUrl={project.cover_image_url}
                onChange={(value) => { updateCover(value) }}
              />
              <div className="px-6 py-4">
                <div className="flex justify-end space-x-3">
                  <SecondaryButton href={route('editor.projects.show', [project.id])}>
                    Cancel
                  </SecondaryButton>
                  <PrimaryButton type="submit">
                    Save
                  </PrimaryButton>
                </div>
              </div>
            </form>
          </div>
        </Container>
      </Admin>
    </>
  )
}

// resources/js/Pages/Editor/Content/Collections/Edit.vue
<script setup>
import AdminLayout from '@/Layouts/Admin.vue';
import { Head } from '@inertiajs/vue3';
import BreezeInput from '@/Components/Input.vue';
import BreezeInputError from '@/Components/InputError.vue';
import BreezeLabel from '@/Components/Label.vue';
import PrimaryButton from '@/Components/Buttons/PrimaryButton.vue';
import SecondaryButton from '@/Components/Buttons/SecondaryButton.vue';
import { router } from '@inertiajs/vue3';
import Header3 from '@/Components/Headers/Header3.vue';

const props = defineProps({
    collection: Object,
});

const submit = () => {
    router.put(route('editor.collections.update', [props.collection.id]), props.collection);
}
</script>

<template>
    <Head :title="`Admin - Edit ${collection.name}`" />

    <AdminLayout>
        <div class="w-full py-8 px-4 sm:px-6 lg:px-8">
            <Header3> Edit Collection: {{ collection.name }} </Header3>
            <div class="mt-4 bg-white shadow overflow-hidden sm:rounded-lg">
                <form @submit.prevent="submit" class="sm:divide-y sm:divide-gray-200">
                    <div class="px-6 sm:grid sm:grid-cols-5 sm:gap-4 sm:items-start sm:border-t sm:border-gray-200 sm:py-4">
                        <BreezeLabel for="name" value="Collection name" class="sm:mt-px sm:pt-2" />
                        <div class="mt-1 sm:mt-0 sm:col-span-4">
                            <BreezeInput type="text" v-model="collection.name" id="name" class="block w-full" />
                            <BreezeInputError class="mt-1" :message="collection.errors?.name" />
                        </div>
                    </div>
                    <div class="px-6 py-4 sm:border-t sm:border-gray-200">
                        <div class="flex justify-end">
                            <SecondaryButton :href="route('editor.collections.show', [collection.id])" as="link">Cancel</SecondaryButton>
                            <PrimaryButton type="submit" class="ml-3">Save</PrimaryButton>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </AdminLayout>
</template>
