// resources/js/Pages/Editor/Content/Collections/Show.vue
<script setup>
import { computed, ref } from 'vue';
import { DialogTitle } from '@headlessui/vue';
import { ArchiveBoxIcon, PencilSquareIcon, PlusCircleIcon } from '@heroicons/vue/24/solid';
import { router } from '@inertiajs/vue3';
import { Head, Link, useForm } from '@inertiajs/vue3';
import AdminLayout from '@/Layouts/Admin.vue';
import DangerModal from '@/Components/Modals/DangerModal.vue';
import SecondaryButton from '@/Components/Buttons/SecondaryButton.vue';
import TableHeader from '@/Components/Tables/TableHeader.vue';
import Table from '@/Components/Tables/Table.vue';
import TableHead from '@/Components/Tables/TableHead.vue';
import TableBody from '@/Components/Tables/TableBody.vue';
import SecondaryButtonWithDropdown from '@/Components/Buttons/SecondaryButtonWithDropdown.vue';
import Header3 from '@/Components/Headers/Header3.vue';

const props = defineProps({
    collection: Object,
    errors: Object,
    success: Object
});

let sortedProjects = computed(() => props.collection.projects.sort((a, b) => a.order - b.order));

const open = ref(false);

const close = () => {
    open.value = false;
}
const destroy = () => {
    router.delete(route('editor.collections.destroy', [props.collection.id]));
}

const updateOrder = (updated_project, sibling_project) => {
    let updateForm = useForm({
        _method: "PUT",
        updated_project,
        sibling_project
    });

    updateForm.post(route('editor.projects.update-order', [updated_project]), {
        preserveScroll: true
    });
}

const moveDown = (orderNumber) => {
    let index = sortedProjects.value.findIndex(project => project.order === orderNumber);

    sortedProjects.value[index].order++;
    sortedProjects.value[index + 1].order--;

    updateOrder(sortedProjects.value[index + 1], sortedProjects.value[index]);
}
const moveUp = (orderNumber) => {
    let index = sortedProjects.value.findIndex(project => project.order === orderNumber);

    sortedProjects.value[index].order--;
    sortedProjects.value[index - 1].order++;

    updateOrder(sortedProjects.value[index - 1], sortedProjects.value[index]);
}

const actions = [
    [
        { name: 'Edit', as: 'link', icon: PencilSquareIcon, href: route('editor.collections.edit', [props.collection.id]) }
    ],
    [
        { name: 'Archive', as: 'emitter', icon: ArchiveBoxIcon, emit: 'open' }
    ]
];
const projectCells = {
    name: 'Name'
}
const draftCells = {
    name: 'Name',
    user: 'Author',
    updated_at: 'Last Updated'
}

const tableActions = {
    view: true,
    edit: true
}
</script>

<template>
    <Head :title="`Admin - ${collection.name}`" />

    <AdminLayout>
        <div class="w-full py-8 px-4 sm:px-6 lg:px-8">
            <div>
                <div class="-ml-4 flex items-center justify-between flex-wrap sm:flex-nowrap">
                    <div class="ml-4">
                        <Header3> Collection Details: {{ collection.name }} </Header3>
                    </div>
                    <div class="ml-4">
                        <SecondaryButtonWithDropdown button-text="Options" :actions="actions" @open="open = true" />
                    </div>
                </div>
                <div class="mt-4 bg-white shadow overflow-hidden sm:rounded-lg">
                    <dl class="sm:divide-y sm:divide-gray-200">
                        <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                            <dt class="text-sm font-medium text-gray-500">Name</dt>
                            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"> {{ collection.name }} </dd>
                        </div>
                    </dl>
                </div>
            </div>

            <div class="mt-12">
                <TableHeader header="Projects" addText="Add project" :add-route="route('editor.drafts.create', {type: 'project', parent_id: collection.id})" />
                <Table class="mt-2">
                    <TableHead :cells="projectCells" :actions="true" :order="true" />
                    <TableBody :cells="projectCells" :rows="sortedProjects" routeType="editor.projects" :actions="tableActions" :order="true" @down="moveDown($event)" @up="moveUp($event)" />
                </Table>
            </div>

            <div v-if="collection.child_drafts.length" class="mt-12">
                <TableHeader header="Project Drafts" />
                <Table class="mt-2">
                    <TableHead :cells="draftCells" :actions="true" />
                    <TableBody :cells="draftCells" :rows="collection.child_drafts" routeType="editor.drafts" :actions="tableActions" />
                </Table>
            </div>
        </div>

        <Teleport to="body" v-if="collection.child_drafts.length">
            <DangerModal :open="open" action-text="Archive" emit-name="delete" @close="close" @delete="destroy">
                <DialogTitle as="h3" class="text-lg leading-6 font-medium text-gray-900"> Archive collection </DialogTitle>
                <div class="mt-2">
                    <p class="text-sm text-gray-500">Are you sure you want to archive {{ collection.name }}?</p>
                </div>
            </DangerModal>
        </Teleport>
    </AdminLayout>
</template>

// resources/js/Pages/Editor/Content/Collections/Show.tsx
import { type FormEventHandler, type ReactElement, useState } from 'react'
import { Dialog } from '@headlessui/react'
import { Head, router, useForm } from '@inertiajs/react'
import Admin from '@/Layouts/Admin'
import Container from '@/Components/Container'
import { Header3 } from '@/Components/Typography/Headers'
import SecondaryButtonWithDropdown from '@/Components/Buttons/SecondaryButtonWithDropdown'
import TableHeader from '@/Components/Tables/TableHeader'
import Table from '@/Components/Tables/Table'
import TableHead from '@/Components/Tables/TableHead'
import TableBody from '@/Components/Tables/TableBody'
import DangerModal from '@/Components/Modals/Danger'
import { type Actions, type Cells, type Collection, type PageProps, type Project } from '@/types'

export default function CollectionShow ({ auth, collection }: PageProps<{ collection: Collection }>): ReactElement {
  const [confirmCollectionArchive, setConfirmCollectionArchive] = useState(false)

  const updateOrder = (updatedProject: Project, siblingProject: Project): void => {
    const { put } = useForm({
      updatedProject,
      siblingProject
    })

    put(route('editor.projects.update-order', [updatedProject]), {
      preserveScroll: true
    })
  }

  const archive: FormEventHandler = (e) => {
    e.preventDefault()

    router.delete(route('editor.collections.destroy', [collection.id]), {
      onSuccess: () => { setConfirmCollectionArchive(false) },
      preserveState: true
    })
  }

  const sortedProjects = collection.projects.sort((a, b) => a.order - b.order)

  const findProjectIndex = (orderNumber: number): number => {
    return sortedProjects.findIndex(project => project.order === orderNumber)
  }

  const moveDown = (orderNumber: number): void => {
    const index = findProjectIndex(orderNumber)

    sortedProjects[index].order++
    sortedProjects[index + 1].order--

    updateOrder(sortedProjects[index + 1], sortedProjects[index])
  }

  const moveUp = (orderNumber: number): void => {
    const index = findProjectIndex(orderNumber)

    sortedProjects[index].order--
    sortedProjects[index - 1].order++

    updateOrder(sortedProjects[index - 1], sortedProjects[index])
  }

  const actions = [
    [
      { name: 'Edit', as: 'link', icon: 'PencilSquareIcon', href: route('editor.collections.edit', [collection.id]) }
    ],
    [
      { name: 'Archive', as: 'emitter', icon: 'ArchiveBoxIcon', emit: () => { setConfirmCollectionArchive(true) } }
    ]
  ]

  const projectCells: Cells = {
    name: 'Name'
  }
  const draftCells: Cells = {
    name: 'Name',
    user: 'Author',
    updated_at: 'Last Updated'
  }

  const tableActions: Actions = {
    view: true,
    edit: true
  }

  return (
    <>
      <Head title={`Admin - ${collection.name}`}/>

      <Admin user={auth.user}>
        <Container>
          <div>
            <div className="-ml-4 flex items-center justify-between flex-wrap sm:flex-nowrap">
              <div className="ml-4">
                <Header3>
                  Collection Details: {collection.name}
                </Header3>
              </div>
              <div className="ml-4">
                <SecondaryButtonWithDropdown
                    buttonText="Options"
                    actions={actions}
                />
              </div>
            </div>
            <div className="mt-4 bg-white shadow overflow-hidden sm:rounded-lg">
              <dl className="sm:divide-y sm:divide-gray-200">
                <div className="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                  <dt className="text-sm font-medium text-gray-500">
                    Name
                  </dt>
                  <dd className="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                    {collection.name}
                  </dd>
                </div>
              </dl>
            </div>
          </div>

          <div className="mt-12">
            <TableHeader
              header="Projects"
              addText="Add project"
              addRoute={route(
                'editor.drafts.create',
                { type: 'project', parent_id: collection.id })}
            />
            <Table className="mt-2">
              <TableHead cells={projectCells} actions={true} order={true}/>
              <TableBody
                cells={projectCells}
                rows={sortedProjects}
                routeType="editor.projects"
                actions={tableActions}
                order={true}
                moveDown={() => moveDown}
                moveUp={() => moveUp}
              />
            </Table>
          </div>

          {collection.child_drafts.length > 0 ? (
            <div className="mt-12">
              <TableHeader header="Project Drafts"/>
              <Table className="mt-2">
                <TableHead cells={draftCells} actions={true}/>
                <TableBody
                  cells={draftCells}
                  rows={collection.child_drafts}
                  routeType="editor.drafts"
                  actions={tableActions}
                />
              </Table>
            </div>
          ) : null}
        </Container>
      </Admin>

      <DangerModal dangerButtonText="Archive" open={confirmCollectionArchive} setOpen={setConfirmCollectionArchive} destroy={archive}>
        <Dialog.Title as="h3" className="text-lg font-medium leading-6 text-gray-900">
          Archive Collection
        </Dialog.Title>
        <div className="mt-2">
          <p className="text-sm text-gray-500">
            Are you sure you want to archive {collection.name}?
          </p>
        </div>
      </DangerModal>
    </>
  )
}
