// resources/js/Components/Forms/Choices/Exercises.vue
<script setup>
import Header from '@/Components/Forms/Choices/ContentBlockHeader.vue';
import TextEditor from '@/Components/TextEditor.vue';

const props = defineProps(['modelValue']);

const emit = defineEmits(['delete', 'update:modelValue']);

const update = () => {
    emit('update:modelValue', props.modelValue);
}
</script>

<template>
    <div class="flex flex-col">
        <div>
            <Header color="emerald" @remove="$emit('delete')">Exercises</Header>
        </div>
        <div class="w-full border-2 border-emerald-200 rounded-b rounded-tr">
            <TextEditor v-model="modelValue" @update:model-value="update" active-color="text-emerald-700 bg-emerald-200 hover:bg-emerald-300 focus:ring-emerald-300" />
        </div>
    </div>
</template>

// resources/js/Components/Forms/Choices/Exercises.tsx
import {type ReactElement} from "react";
import ContentBlockHeader from "@/Components/Forms/Choices/ContentBlockHeader";
import TextEditor from "@/Components/Forms/TextEditor";

export default function Exercises({value, remove, index, update}: {
  value: string,
  index: number,
  update: (index: number, value: string) => {},
  remove?: (index: number) => {}
}): ReactElement {
  const updateExercises = (value: string) => {
    update(index, value)
  }

  return (
    <div className="flex flex-col">
      <ContentBlockHeader color="emerald" remove={() => remove(index)}>
        Exercises
      </ContentBlockHeader>
      <div className="w-full border-2 border-emerald-200 rounded-b-md rounded-tr-md">
        <TextEditor value={value} update={updateExercises}/>
      </div>
    </div>
  );
}
