// resources/js/Components/Forms/Choices/ResourceList.vue
<script setup>
import { ref } from 'vue';
import Header from '@/Components/Forms/Choices/ContentBlockHeader.vue';
import AddResourceCreate from '@/Components/Forms/Choices/AddResourceCreate.vue';
import ResourceListWrapper from '@/Components/Lists/ResourceListWrapper.vue';
import ResourceListItem from '@/Components/Lists/ResourceListItem.vue';

const emit = defineEmits(['delete','update']);

const show = ref(true);

const resources = ref([]);

const update = () => {
    emit('update', resources);
}

const addResource = (event) => {
    resources.value.push(event);

    update();
}
</script>

<template>
    <div class="flex flex-col">
        <div>
            <Header color="purple" @remove="$emit('delete')">Resource List</Header>
        </div>
        <div class="w-full p-4 border-2 border-purple-200 rounded-b rounded-tr">
            <div v-if="resources.length > 0" class="pb-4">
                <ResourceListWrapper>
                    <ResourceListItem v-for="resource in resources" :key="resource.id" :resource="resource" />
                </ResourceListWrapper>
            </div>
            <AddResourceCreate v-if="show" @add="addResource($event)" />
        </div>
    </div>
</template>

// resources/js/Components/Forms/Choices/ResourceList.tsx
import {type ReactElement} from "react";
import ContentBlockHeader from "@/Components/Forms/Choices/ContentBlockHeader";
import ResourceListItem from "@/Components/Lists/ResourceListItem";
import AddResourceItem from "@/Components/Forms/Choices/AddResourceItem";
import {type Resource} from "@/types";
import classNames from "@/Utils/classNames";

export default function ResourceList({value, remove, index, update}: {
  value: Resource[],
  index: number,
  update: (index: number, value: string|Resource[]) => {},
  remove?: (index: number) => {}
}): ReactElement {
  const addResource = (resource: Resource) => {
    value.push(resource);

    update(index, value);
  }

  return (
    <div className="flex flex-col">
      <ContentBlockHeader color="purple" remove={() => remove!(index)}>
        Resource List
      </ContentBlockHeader>
      <div className="w-full p-4 border-2 border-purple-200 rounded-b-md rounded-tr-md">
        <ul className={classNames(
          value.length > 0 ? 'border border-gray-300 mb-2' : '',
          'divide-y divide-gray-300 rounded-md'
        )}>
          {value.map((resource, index) => (
            <ResourceListItem key={index} resource={resource}/>
          ))}
        </ul>
        <AddResourceItem add={(resource: Resource) => addResource(resource)}/>
      </div>
    </div>
  );
}
