// resources/js/Components/Forms/Choices/TextBlock.vue
<script setup>
import Header from '@/Components/Forms/Choices/ContentBlockHeader.vue';
import TextEditor from '@/Components/TextEditor.vue';

const props = defineProps(['item']);

const emit = defineEmits(['delete', 'update']);

const update = (updatedData) => {
    emit('update', updatedData);
}
</script>

<template>
    <div class="flex flex-col">
        <div>
            <Header color="red" @remove="$emit('delete')">Text Block</Header>
        </div>
        <div class="w-full border-2 border-red-200 rounded-b rounded-tr">
            <TextEditor v-model="item.data" @update:model-value="update($event)" active-color="text-red-700 bg-red-200 hover:bg-red-300 focus:ring-red-300" />
        </div>
    </div>
</template>

// resources/js/Components/Forms/Choices/TextBlock.tsx
import {type ReactElement} from "react";
import ContentBlockHeader from "@/Components/Forms/Choices/ContentBlockHeader";
import TextEditor from "@/Components/Forms/TextEditor";

export default function TextBlock({value, remove, index, update}: {
  value: string,
  index: number,
  update: (index: number, value: string) => {},
  remove?: (index: number) => {}
}): ReactElement {
  const updateTextBlock = (value: string) => {
    update(index, value);
  }

  return (
    <div className="flex flex-col">
      <ContentBlockHeader color="red" remove={() => remove!(index)}>
        Text Block
      </ContentBlockHeader>
      <div className="w-full border-2 border-red-200 rounded-b rounded-tr">
        <TextEditor value={value} update={updateTextBlock}/>
      </div>
    </div>
  )
}
