// resources/js/Pages/Editor/Content/Projects/Edit.vue
<script setup>
import { ref, watch } from 'vue';
import AdminLayout from '@/Layouts/Admin';
import { Head } from '@inertiajs/inertia-vue3';
import BreezeInput from '@/Components/Input';
import BreezeInputError from '@/Components/InputError';
import BreezeLabel from '@/Components/Label';
import PrimaryButton from '@/Components/PrimaryButton';
import SecondaryButton from '@/Components/SecondaryButton';
import { Listbox, ListboxButton, ListboxLabel, ListboxOption, ListboxOptions } from '@headlessui/vue';
import { CheckIcon, SelectorIcon } from '@heroicons/vue/solid';
import { Inertia } from '@inertiajs/inertia';

const props = defineProps({
    projectables: Array,
    project: Object,
});

const selected = ref(props.projectables[
    props.projectables.findIndex(
        projectable => projectable.id === props.project.projectable.id
    )
]);

const submit = () => {
    Inertia.put(route('editor.projects.update', [props.project.slug]), props.project);
}

watch(selected, (newSelected, oldSelected) => {
    Object.assign(props.project.projectable, newSelected);
});
</script>

<template>
    <Head :title="`Admin - Projects - Edit ${project.name}`" />

    <AdminLayout type="admin">
        <div class="w-full py-8 px-4 sm:px-6 lg:px-8">
            <h3 class="text-lg leading-6 font-medium text-gray-900"> Edit Project: {{ project.name }} </h3>
            <div class="mt-4 bg-white rounded-md shadow">
                <form @submit.prevent="submit" class="sm:divide-y sm:divide-gray-200">
                    <div class="px-6 sm:grid sm:grid-cols-5 sm:gap-4 sm:items-start sm:border-t sm:border-gray-200 sm:py-4">
                        <BreezeLabel for="name" value="Project name" class="sm:mt-px sm:pt-2" />
                        <div class="mt-1 sm:mt-0 sm:col-span-4">
                            <BreezeInput type="text" v-model="project.name" id="name" class="block w-full" />
                            <BreezeInputError class="mt-1" :message="project.errors?.name" />
                        </div>
                    </div>
                    <div class="px-6 sm:border-t sm:border-gray-200 sm:pt-4">
                        <Listbox as="div" class="sm:grid sm:grid-cols-5 sm:gap-4 sm:items-start" v-model="selected">
                            <ListboxLabel class="block text-sm font-medium text-gray-700 sm:mt-px sm:pt-2"> Belongs to </ListboxLabel>
                            <div class="mt-1 relative sm:col-span-4 sm:mt-0">
                                <ListboxButton class="bg-white relative w-full border border-gray-300 rounded-md shadow-sm pl-3 pr-10 py-2 text-left cursor-default focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
                                    <span class="block truncate">{{ selected.name }}</span>
                                    <span class="absolute inset-y-0 right-0 flex items-center pr-2 pointer-events-none">
                                        <SelectorIcon class="h-5 w-5 text-gray-400" aria-hidden="true" />
                                    </span>
                                </ListboxButton>

                                <transition leave-active-class="transition ease-in duration-100" leave-from-class="opacity-100" leave-to-class="opacity-0">
                                    <ListboxOptions class="absolute z-10 mt-1 w-full bg-white shadow-lg max-h-60 rounded-md py-1 text-base ring-1 ring-black ring-opacity-5 overflow-auto focus:outline-none sm:text-sm">
                                        <ListboxOption as="template" v-for="projectable in projectables" :key="projectable.id" :value="projectable" v-slot="{ active, selected }">
                                            <li :class="[active ? 'text-white bg-indigo-600' : 'text-gray-900', 'cursor-default select-none relative py-2 pl-3 pr-9']">
                                                <span :class="[selected ? 'font-semibold' : 'font-normal', 'block truncate']">
                                                    {{ projectable.name }}
                                                </span>

                                                <span v-if="selected" :class="[active ? 'text-white' : 'text-indigo-600', 'absolute inset-y-0 right-0 flex items-center pr-4']">
                                                    <CheckIcon class="h-5 w-5" aria-hidden="true" />
                                                </span>
                                            </li>
                                        </ListboxOption>
                                    </ListboxOptions>
                                </transition>
                            </div>
                        </Listbox>
                    </div>
                    <div class="px-6 py-4 mt-4 sm:border-t sm:border-gray-200">
                        <div class="flex justify-end">
                            <SecondaryButton :href="route('editor.projects.show', [project.slug])" as="link">Cancel</SecondaryButton>
                            <PrimaryButton type="submit" class="ml-3">Save</PrimaryButton>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </AdminLayout>
</template>

// resources/js/Pages/Admin/Assignments/Edit.tsx
import { type FormEventHandler, Fragment, type ReactElement } from 'react'
import { Listbox, Transition } from '@headlessui/react'
import { CheckIcon, ChevronUpDownIcon } from '@heroicons/react/24/solid'
import { Head, useForm } from '@inertiajs/react'
import Admin from '@/Layouts/Admin'
import Container from '@/Components/Container'
import { Header3 } from '@/Components/Typography/Headers'
import InputError from '@/Components/Forms/InputError'
import InputLabel from '@/Components/Forms/InputLabel'
import FormText from '@/Components/Forms/FormText'
import SecondaryButton from '@/Components/Buttons/SecondaryButton'
import PrimaryButton from '@/Components/Buttons/PrimaryButton'
import classNames from '@/Utils/classNames'
import { type Assignment, type PageProps, type User } from '@/types'

export default function AssignmentEdit ({ auth, assignment, editors }: PageProps<{
  assignment: Assignment
  editors: User[]
}>): ReactElement {
  const { data, setData, errors } = useForm({
    editor: assignment.user
  })

  const submit: FormEventHandler = (e) => {
    e.preventDefault()
  }

  return (
    <>
      <Head title="Edit Assignment"/>

      <Admin user={auth.user}>
        <Container>
          <Header3>
            Edit Assignment
          </Header3>
          <div className="mt-4 bg-white shadow sm:rounded-lg">
            <form onSubmit={submit} className="sm:divide-y sm:divide-gray-200">
              <div className="px-6 sm:grid sm:grid-cols-5 sm:gap-4 sm:items-start sm:py-4">
                <Listbox value={data.editor} onChange={(value) => {
                  setData('editor', value)
                }}>
                  {({ open }) => (
                    <>
                      <Listbox.Label className="block text-sm font-medium leading-6 text-gray-700 sm:mt-px sm:pt-1.5">
                        Editor
                      </Listbox.Label>
                      <div className="relative mt-1 sm:mt-0 sm:col-span-2">
                        <Listbox.Button
                          className="relative w-full bg-white border border-gray-300 rounded-md shadow-sm pl-3 pr-10 py-2 text-left cursor-default focus:outline-none focus:ring-1 focus:ring-blue-500 focus:border-blue-500 sm:text-sm">
                          {data.editor !== null ? (
                            <span className="block truncate">
                              {data.editor.name}
                            </span>
                          ) : (
                            <span className="block truncate text-gray-500">
                              Select an editor for this assignment
                            </span>
                          )}
                          <span className="absolute inset-y-0 right-0 flex items-center pr-2 pointer-events-none">
                            <ChevronUpDownIcon className="h-5 w-5 text-gray-400"/>
                          </span>
                        </Listbox.Button>

                        <Transition
                          show={open}
                          as={Fragment}
                          leave="transition ease-in duration-100"
                          leaveFrom="opacity-100"
                          leaveTo="opacity-0"
                        >
                          <Listbox.Options
                            className="absolute z-10 mt-1 max-h-60 w-full overflow-auto rounded-md bg-white py-1 text-base shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none sm:text-sm">
                            {editors.map((editor) => (
                              <Listbox.Option
                                key={editor.id}
                                className={({ active }) =>
                                  classNames(
                                    active ? 'bg-blue-600 text-white' : 'text-gray-900',
                                    'relative cursor-default select-none py-2 pl-3 pr-9'
                                  )
                                }
                                value={editor}
                              >
                                {({ active, selected }) => (
                                  <>
                                    <span
                                      className={classNames(selected ? 'font-semibold' : 'font-normal', 'block truncate')}>
                                      {editor.name}
                                    </span>

                                    {selected ? (
                                      <span
                                        className={classNames(
                                          active ? 'text-white' : 'text-blue-600',
                                          'absolute inset-y-0 right-0 flex items-center pr-4'
                                        )}
                                      >
                                        <CheckIcon className="h-5 w-5" aria-hidden="true"/>
                                      </span>
                                    ) : null}
                                  </>
                                )}
                              </Listbox.Option>
                            ))}
                          </Listbox.Options>
                        </Transition>
                      </div>
                    </>
                  )}
                </Listbox>
                <InputError message={errors.editor} className="mt-1"/>
              </div>

              <div className="px-6 sm:grid sm:grid-cols-5 sm:gap-4 sm:items-start sm:py-4">
                <InputLabel label="Belongs to" className="sm:mt-px sm:pt-2"/>
                <div className="mt-1 sm:mt-0 sm:col-span-4">
                  <FormText value={assignment.assignable.name} className="block w-full"/>
                </div>
              </div>

              <div className="px-6 py-4">
                <div className="flex justify-end">
                  <SecondaryButton href={route('admin.assignments.index')}>
                    Cancel
                  </SecondaryButton>
                  <PrimaryButton type="submit" className="ml-3">
                    Save
                  </PrimaryButton>
                </div>
              </div>
            </form>
          </div>
        </Container>
      </Admin>
    </>
  )
}
