// resources/js/Components/ChoiceEdit.tsx
import {type FormEventHandler, type ReactElement, useState} from "react";
import {useForm} from "@inertiajs/react";
import TextInput from "@/Components/Forms/TextInput";
import InputLabel from "@/Components/Forms/InputLabel";
import InputError from "@/Components/Forms/InputError";
import Summary from "@/Components/Forms/Choices/Summary";
import SecondaryButton from "@/Components/Buttons/SecondaryButton";
import PrimaryButton from "@/Components/Buttons/PrimaryButton";
import TextBlock from "@/Components/Forms/Choices/TextBlock";
import Header from "@/Components/Forms/Choices/Header";
import Exercises from "@/Components/Forms/Choices/Exercises";
import QUIKLinks from "@/Components/Forms/Choices/QUIKLinks";
import ResourceList from "@/Components/Forms/Choices/ResourceList";
import {type Choice, ChoiceContent, type Resource} from "@/types";

export default function ChoiceEdit({choice, close}: {
  choice: Choice;
  close: () => {};
}): ReactElement {
  const [choiceData, setChoiceData] = useState<Choice>({
    ...choice,
  });

  const updateProperty = (index: number, value: string|Resource[]): void => {
    let { content } = choiceData;
    content[index].data = value;

    setChoiceData({
      ...choiceData,
      content,
    });
  }

  const submit = (e): FormEventHandler => {
    e.preventDefault();
    console.log(choiceData);
  }

  return (
    <div className="border-t border-gray-200">
      <form onSubmit={submit} className="sm:divide-y sm:divide-gray-200">
        <div className="px-6 sm:grid sm:grid-cols-8 sm:gap-4 sm:items-start sm:py-4">
          <InputLabel label="Name" className="sm:mt-px sm:pt-2"/>
          <div className="mt-1 space-y-4 sm:mt-0 sm:col-span-7">
            <TextInput
              value={choiceData.name}
              className="block w-full"
              isFocused
              onChange={(e) => setChoiceData({
                ...choiceData,
                name: e.target.value,
              })}
            />
          </div>
        </div>
      </form>

      <div className="px-6 sm:grid sm:grid-cols-8 sm:gap-4 sm:items-start sm:py-4">
        <InputLabel label="Content" className="sm:mt-px sm:pt-2"/>
        <div className="mt-1 space-y-4 sm:mt-0 sm:col-span-7">
          {choiceData.content.map((item, idx): void => {
            if (item.type === 'summary') return <Summary key={idx} index={idx} value={item.data} update={(index, value) => updateProperty(index, value)}/>
            if (item.type === 'text') return <TextBlock key={idx} index={idx} value={item.data} update={(index, value) => updateProperty(index, value)}/>
            if (item.type === 'resources') return <ResourceList key={idx} index={idx} value={item.data} update={(index, value) => updateProperty(index, value)}/>
            if (item.type === 'header') return <Header key={idx} index={idx} value={item.data} update={(index, value) => updateProperty(index, value)}/>
            if (item.type === 'exercises') return <Exercises key={idx} index={idx} value={item.data} update={(index, value) => updateProperty(index, value)}/>
            if (item.type === 'quiklinks') return <QUIKLinks key={idx} index={idx} value={item.data} update={(index, value) => updateProperty(index, value)}/>
          })}
        </div>
      </div>

      <div className="px-6 py-4">
        <div className="flex justify-end space-x-3">
          <SecondaryButton onClick={close}>
            Cancel
          </SecondaryButton>
          <PrimaryButton type="submit">
            Save
          </PrimaryButton>
        </div>
      </div>
    </div>
  );
}

// resources/js/Components/ChoiceEdit.vue
<script setup>
import { onMounted, ref } from 'vue';
import { useForm } from '@inertiajs/vue3';
import BreezeInput from '@/Components/Input.vue';
import BreezeInputError from '@/Components/InputError.vue';
import BreezeLabel from '@/Components/Label.vue';
import TextEditor from '@/Components/TextEditor.vue';
import PrimaryButton from '@/Components/Buttons/PrimaryButton.vue';
import SecondaryButton from '@/Components/Buttons/SecondaryButton.vue';
import AddResource from '@/Components/Forms/AddResource.vue';
import ResourceListWrapper from './Lists/ResourceListWrapper.vue';
import ResourceListItem from './Lists/ResourceListItem.vue';
import Summary from '@/Components/Forms/Choices/Summary.vue';
import AddSummaryButton from '@/Components/Buttons/Choices/AddSummaryButton.vue';
import TextBlock from '@/Components/Forms/Choices/TextBlock.vue';
import AddTextBlockButton from '@/Components/Buttons/Choices/AddTextBlockButton.vue';
import Images from '@/Components/Forms/Choices/Images.vue';
import ResourceList from '@/Components/Forms/Choices/ResourceList.vue';
import AddResourceListButton from '@/Components/Buttons/Choices/AddResourceListButton.vue';
import Header from '@/Components/Forms/Choices/Header.vue';
import AddHeaderButton from '@/Components/Buttons/Choices/AddHeaderButton.vue';
import Exercises from '@/Components/Forms/Choices/Exercises.vue';
import AddExercisesButton from '@/Components/Buttons/Choices/AddExercisesButton.vue';
import QUIKLinks from '@/Components/Forms/Choices/QUIKLinks.vue';
import AddQuikLinksButton from '@/Components/Buttons/Choices/AddQuikLinksButton.vue';

const props = defineProps({
    currentChoice: Object
});

const emits = defineEmits(['close']);

const show = ref(false);

const choice = useForm({
    ...props.currentChoice
});

const hasSummary = ref(false);
const hasExercises = ref(false);

onMounted(() => {
    for (let item of choice.content) {
        if (item.type === 'summary') {
            hasSummary.value = true;
        } else if (item.type === 'exercises') {
            hasExercises.value = true;
        }
    }
});

const addProperty = (type) => {
    type === 'resources' ? choice.content.push({ 'type': type, 'data': [] }) : choice.content.push({ 'type': type, 'data': "" });

    if (type === 'summary') {
        hasSummary.value = true;
    }
    if (type === 'exercises') {
        hasExercises.value = true;
    }
}

const updateProperty = (index, data) => {
    choice.content[index].data = data;
}

const updateImages = (data) => {
    choice.images = data;
}

const deleteProperty = (index) => {
    if (choice.content[index].type === 'summary') {
        hasSummary.value = false;
    }
    if (choice.content[index].type === 'exercises') {
        hasExercises.value = false;
    }

    choice.content.splice(index, 1);
}

const submit = () => {
    choice.put(route('editor.choices.update', [choice.id]), {
        preserveScroll: true,
    });
}

const addResource = (event) => {
    choice.resourceList.push(event);
    show.value = false;
}
</script>

<template>
    <div class="border-t border-gray-200">
        <form @submit.prevent="submit" class="sm:divide-y sm:divide-gray-200">
            <div class="px-6 sm:grid sm:grid-cols-8 sm:gap-4 sm:items-start sm:py-4">
                <BreezeLabel for="name" value="Name" class="sm:mt-px sm:pt-2" />
                <div class="mt-1 sm:mt-0 sm:col-span-7">
                    <BreezeInput type="text" v-model="choice.name" id="name" class="block w-full" />
                    <BreezeInputError class="mt-1" :message="choice.errors?.name" />
                </div>
            </div>
            <div class="px-6 sm:grid sm:grid-cols-8 sm:gap-4 sm:items-start sm:py-4">
                <BreezeLabel for="content" value="Content" class="sm:mt-px sm:pt-2" />
                <div class="mt-1 space-y-4 sm:mt-0 sm:col-span-7">
                    <template v-for="(item, index) in choice.content" :key="index">
                        <Summary v-if="item.type === 'summary'" @delete="deleteProperty(index)" @update="updateProperty(index, $event)" :item="item" />
                        <TextBlock v-else-if="item.type === 'text'" @delete="deleteProperty(index)" @update="updateProperty(index, $event)" :item="item" />
                        <ResourceList v-if="item.type === 'resources'" @delete="deleteProperty(index)" @update="updateProperty(index, $event)" :item="item" />
                        <Header v-else-if="item.type === 'header'" @delete="deleteProperty(index)" @update="updateProperty(index, $event)" :item="item" />
                        <Exercises v-else-if="item.type === 'exercises'" @delete="deleteProperty(index)" @update="updateProperty(index, $event)" :item="item" />
                        <QUIKLinks v-else-if="item.type === 'quiklinks'" @delete="deleteProperty(index)" @update="updateProperty(index, $event)" :item="item" />
                    </template>
                    <div class="space-x-2">
                        <AddSummaryButton v-if="! hasSummary" @click.prevent="addProperty('summary')" />
                        <AddTextBlockButton @click.prevent="addProperty('text')" />
                        <AddResourceListButton @click.prevent="addProperty('resources')" />
                        <AddHeaderButton @click.prevent="addProperty('header')" />
                        <AddExercisesButton v-if="! hasExercises" @click.prevent="addProperty('exercises')" />
                        <AddQuikLinksButton @click.prevent="addProperty('quiklinks')" />
                    </div>
                </div>
            </div>
            <div class="px-6 py-4">
                <div class="flex justify-end">
                    <SecondaryButton type="button" @click="$emit('close')">Cancel</SecondaryButton>
                    <PrimaryButton type="submit" class="ml-3">Save</PrimaryButton>
                </div>
            </div>
        </form>
    </div>
</template>
