// resources/js/Components/Buttons/EditorButton.tsx
import {type PropsWithChildren, type ReactElement} from "react";
import classNames from "@/Utils/classNames";

export default function EditorButton ({ children, className, onClick }: PropsWithChildren<{ className: string, onClick: () => void }>): ReactElement {
  return (
    <button type="button" onClick={onClick} className={classNames(
      'w-8 h-8 inline-flex justify-center items-center gap-x-2 text-sm font-semibold rounded-full border border-transparent text-gray-800 hover:bg-gray-100 disabled:opacity-50 disabled:pointer-events-none',
      className
    )}>
      {children}
    </button>
  )
}

// resources/js/Components/EditorButton.vue
<script setup>
defineProps({
    active: Boolean,
    notActive: Boolean,
});
</script>

<template>
    <button type="button" :disabled="notActive" :class="[
        active ?
            'border border-transparent text-white bg-indigo-600 hover:bg-indigo-700 focus:ring focus:ring-indigo-500 focus:ring-opacity-40' :
            'border border-gray-300 text-gray-700 hover:bg-gray-50 bg-white focus:ring focus:ring-gray-300 focus:ring-opacity-40',
        'inline-flex items-center p-1 rounded-md shadow-sm text-xs uppercase font-medium focus:outline-none']">
        <slot />
    </button>
</template>
