// resources/js/Components/Buttons/SecondaryButton.tsx
import { type ButtonHTMLAttributes, type ReactElement } from 'react'
import { Link } from '@inertiajs/react'
import { LockClosedIcon } from '@heroicons/react/24/solid'
import classNames from '@/Utils/classNames'

export default function SecondaryButton ({
  className = '',
  disabled,
  children,
  href = '',
  locked,
  ...props
}: ButtonHTMLAttributes<HTMLButtonElement> & { href?: string, locked?: boolean }): ReactElement {
  const baseStyles = `relative inline-flex bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50 focus:ring focus:ring-gray-300 focus:ring-opacity-40 sm:w-auto ${className}`
  return href !== '' ? (
    <Link
      href={href}
      className={classNames(
        locked === true ? 'pointer-events-none cursor-default' : '',
        baseStyles
      )}
    >
      {locked === true ? (
        <div className="absolute inset-0 w-full h-full flex items-center justify-center bg-gray-200 opacity-70 z-40">
          <LockClosedIcon className="h-4 w-4 opacity-80" aria-hidden="true"/>
        </div>
      ) : null}
      <div className="relative">
        {children}
      </div>
    </Link>
  ) : (
    <button
      {...props}
      className={classNames(
        locked === true ? 'pointer-events-none cursor-default' : '',
        baseStyles
      )}
      disabled={disabled}
    >
      {locked === true ? (
        <div className="absolute inset-0 w-full h-full flex items-center justify-center bg-gray-200 opacity-70 z-40">
          <LockClosedIcon className="h-4 w-4 opacity-80" aria-hidden="true"/>
        </div>
      ) : null}
      <div className="relative">
        {children}
      </div>
    </button>
  )
}

// resources/js/Components/SecondaryButton.vue
<script setup>
import { Link } from '@inertiajs/inertia-vue3';

defineProps({
    as: String,
    href: String,
    type: {
        type: String,
        default: 'submit',
    }
});

const classes = "relative inline-flex bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50 focus:ring focus:ring-gray-300 focus:ring-opacity-40 sm:w-auto";
</script>

<template>
    <Link :href="href" :class="classes" v-if="as === 'link'">
        <slot />
    </Link>
    <button :type="type" :class="classes" v-else>
        <slot />
    </button>
</template>
