// resources/js/Layouts/Admin.vue
<script setup>
import { ref } from 'vue';
import BreezeApplicationLogo from '@/Components/ApplicationLogo.vue';
import BreezeDropdown from '@/Components/Dropdown.vue';
import BreezeDropdownLink from '@/Components/DropdownLink.vue';
import BreezeNavLink from '@/Components/NavLink.vue';
import BreezeResponsiveNavLink from '@/Components/ResponsiveNavLink.vue';
import { Link } from '@inertiajs/inertia-vue3';

const showingNavigationDropdown = ref(false);
const navigation = [
    { name: 'Dashboard', href: route('admin.dashboard'), components: ['Admin/Dashboard'] },
    { name: 'Projects', href: route('admin.projects.index'), components: [
        'Admin/Projects/Index','Admin/Projects/Create','Admin/Projects/Show','Admin/Projects/Edit'
    ]},
    { name: 'Partners', href: route('admin.partners.index'), components: [
        'Admin/Partners/Index','Admin/Partners/Create','Admin/Partners/Show','Admin/Partners/Edit'
    ]},
    { name: 'Collections', href: '#', components: [] },
    { name: 'Navigation', href: '#', components: [] },
];
</script>

<template>
    <div>
        <div class="min-h-screen bg-gray-100">
            <nav class="bg-white border-b border-gray-100">
                <!-- Primary Navigation Menu -->
                <div class="px-4 sm:px-6 lg:px-8">
                    <div class="flex justify-between h-16">
                        <div class="flex">
                            <!-- Logo -->
                            <div class="shrink-0 flex items-center">
                                <Link :href="route('dashboard')">
                                    <BreezeApplicationLogo class="block h-9 w-auto" />
                                </Link>
                            </div>

                            <!-- Navigation Links -->
                            <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                                <!-- <BreezeNavLink :href="route('dashboard')" :active="route().current('dashboard')">
                                    Dashboard
                                </BreezeNavLink> -->
                            </div>
                        </div>

                        <div class="hidden sm:flex sm:items-center sm:ml-6">
                            <!-- Settings Dropdown -->
                            <div class="ml-3 relative">
                                <BreezeDropdown align="right" width="48">
                                    <template #trigger>
                                        <span class="inline-flex rounded-md">
                                            <button type="button" class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-gray-500 bg-white hover:text-gray-700 focus:outline-none transition ease-in-out duration-150">
                                                {{ $page.props.auth.user.name }}

                                                <svg class="ml-2 -mr-0.5 h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                                                    <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                                </svg>
                                            </button>
                                        </span>
                                    </template>

                                    <template #content>
                                        <BreezeDropdownLink :href="route('logout')" method="post" as="button">
                                            Log Out
                                        </BreezeDropdownLink>
                                    </template>
                                </BreezeDropdown>
                            </div>
                        </div>

                        <!-- Hamburger -->
                        <div class="-mr-2 flex items-center sm:hidden">
                            <button @click="showingNavigationDropdown = ! showingNavigationDropdown" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                                <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                                    <path :class="{'hidden': showingNavigationDropdown, 'inline-flex': ! showingNavigationDropdown }" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                                    <path :class="{'hidden': ! showingNavigationDropdown, 'inline-flex': showingNavigationDropdown }" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                                </svg>
                            </button>
                        </div>
                    </div>
                </div>

                <!-- Responsive Navigation Menu -->
                <div :class="{'block': showingNavigationDropdown, 'hidden': ! showingNavigationDropdown}" class="sm:hidden">
                    <div class="pt-2 pb-3 space-y-1">
                        <BreezeResponsiveNavLink :href="route('dashboard')" :active="route().current('dashboard')">
                            Dashboard
                        </BreezeResponsiveNavLink>
                    </div>

                    <!-- Responsive Settings Options -->
                    <div class="pt-4 pb-1 border-t border-gray-200">
                        <div class="px-4">
                            <div class="font-medium text-base text-gray-800">{{ $page.props.auth.user.name }}</div>
                            <div class="font-medium text-sm text-gray-500">{{ $page.props.auth.user.email }}</div>
                        </div>

                        <div class="mt-3 space-y-1">
                            <BreezeResponsiveNavLink :href="route('logout')" method="post" as="button">
                                Log Out
                            </BreezeResponsiveNavLink>
                        </div>
                    </div>
                </div>
            </nav>

            <!-- Page Content -->
            <main class="flex">
                <aside class="hidden lg:flex lg:flex-shrink-0">
                    <div class="flex flex-col w-64">
                        <div class="flex-1 flex flex-col min-h-0">
                            <div class="flex-1 flex flex-col py-8 overflow-y-auto">
                                <nav class="space-y-2 px-4" aria-label="Sidebar">
                                    <Link v-for="item in navigation" :key="item.name" :href="item.href" :class="[item.components.includes($page.component) ? 'bg-gray-200 text-gray-900 font-semibold' : 'text-gray-600 hover:bg-gray-200 hover:text-gray-900', 'flex items-center px-3 py-2 text-sm font-medium rounded-md']" :aria-current="item.current ? 'page' : undefined">
                                        <span class="truncate">
                                            {{ item.name }}
                                        </span>
                                    </Link>
                                </nav>
                            </div>
                        </div>
                    </div>
                </aside>
                <slot />
            </main>
        </div>
    </div>
</template>

// resources/js/Components/Navigation/Admin.tsx
import {Link, usePage} from "@inertiajs/react";
import classNames from "@/Utils/classNames";

export default function AdminNavigation() {
  const {component} = usePage();
  const {canManageEditors, currentUserRole: role} = usePage().props;

  const dashboardLink: string = (role === 'admin' || role === 'super admin' || role === 'developer')
    ? route('admin.dashboard') : route('editor.dashboard');

  const contentComponents: string[] = [
    'Editor/Content/Index',
    'Editor/Content/Collections/Index', 'Editor/Content/Collections/Create', 'Editor/Content/Collections/Show', 'Editor/Content/Collections/Edit',
    'Editor/Content/Projects/Index', 'Editor/Content/Projects/Create', 'Editor/Content/Projects/Show', 'Editor/Content/Projects/Edit',
    'Editor/Content/Goals/Index', 'Editor/Content/Goals/Create', 'Editor/Content/Goals/Show', 'Editor/Content/Goals/Edit',
    'Editor/Content/Choices/Index', 'Editor/Content/Choices/Create', 'Editor/Content/Choices/Show', 'Editor/Content/Choices/Edit',
  ];

  const assignmentComponents: string[] = [
    'Admin/Assignments/Index','Admin/Assignments/Create','Admin/Assignments/Edit','Editor/Assignments/Show',
  ];

  const editorManagementComponents: string[] = [
    'Admin/Editors/Index','Admin/Editors/Create','Admin/Editors/Show','Admin/Editors/Edit'
  ];

  const navigation = [
    {name: 'Dashboard', href: dashboardLink, show: true, components: ['Admin/Dashboard', 'Editor/Dashboard']},
    {name: 'Content', href: route('editor.content.index'), show: true, components: contentComponents},
    {name: 'Assignments', href: route('admin.assignments.index'), show: canManageEditors, components: assignmentComponents},
    {name: 'Admins & Editors', href: route('admin.editors.index'), show: canManageEditors, components: editorManagementComponents},
  ];

  const filteredNavigation = navigation.filter(item => item.show === true);

  return (
    <aside className="hidden lg:flex lg:flex-shrink-0">
      <div className="flex flex-col w-64">
        <div className="flex-1 flex flex-col min-h-0">
          <div className="flex-1 flex flex-col py-8 overflow-y-auto">
            <nav className="space-y-2 px-4" aria-label="Sidebar">
              {filteredNavigation.map((item, index) => (
                <Link
                  key={index}
                  href={item.href}
                  className={classNames(
                    item.components.includes(component) ? 'bg-gray-200 text-gray-900 font-semibold' : 'text-gray-600 hover:bg-gray-200 hover:text-gray-900',
                    'group flex items-center px-3 py-2 text-sm font-medium rounded-md'
                  )}
                >
                  {item.name}
                </Link>
              ))}
            </nav>
          </div>
        </div>
      </div>
    </aside>
  );
}
