// resources/js/Components/Tables/TableHead.tsx
import classNames from "@/Utils/classNames";

export default function TableHead({ cells, actions, order }) {
    return (
        <thead className="bg-gray-50">
            <tr>
                {Object.keys(cells).map((cell, index) => (
                    <th
                        key={index}
                        scope="col"
                        className={classNames(
                            index === 0 ? 'pl-4 pr-3 sm:pl-6' : 'px-3',
                            'py-2.5 text-left text-xs font-medium uppercase tracking-wide text-gray-500'
                        )}
                    >
                        {cell}
                    </th>
                ))}
                {order ? (
                    <th
                        scope="col"
                        className="relative w-8 px-3 py-3 text-left text-xs font-medium uppercase tracking-wide text-gray-500"
                    >
                        Order
                    </th>
                ) : null}
                {actions ? (
                    <th
                        scope="col"
                        className="relative py-2.5 pl-3 pr-4 sm:pr-6"
                    >
                        <span className="sr-only">Manage</span>
                    </th>
                ) : null}
            </tr>
        </thead>
    );
}

// resources/js/Components/Tables/TableHead.vue
<script setup>
defineProps({
    cells: Object,
    actions: Boolean,
    order: Boolean
});
</script>

<template>
    <thead class="bg-gray-50">
        <tr>
            <th v-for="(cell, key, idx) in cells" :key="key" scope="col" :class="[idx === 0 ? 'pl-4 pr-3 sm:pl-6' : 'px-3', 'py-2.5 text-left text-xs font-medium uppercase tracking-wide text-gray-500']"> {{ cell }} </th>
            <th v-if="order" scope="col" class="relative w-8 px-3 py-3 text-left text-xs font-medium uppercase tracking-wide text-gray-500">Order</th>
            <th v-if="actions" scope="col" class="relative py-2.5 pl-3 pr-4 sm:pr-6">
                <span class="sr-only">Manage</span>
            </th>
        </tr>
    </thead>
</template>
