// resources/js/Components/Tables/TableHeader.vue
<script setup>
import { Inertia } from '@inertiajs/inertia';
import PrimaryButton from '@/Components/Buttons/PrimaryButton.vue';

const props = defineProps({
    addLink: String,
    addRoute: String,
    addText: String,
    header: String,
});

const submit = () => {
    Inertia.post(props.addRoute);
}
</script>

<template>
    <div class="sm:flex sm:items-center">
        <div class="sm:flex-auto">
            <h3 class="leading-6 font-medium text-gray-900"> {{ header }} </h3>
        </div>
        <div v-if="addLink && addText" class="ml-4 space-x-2">
            <PrimaryButton :href="addLink" as="link"> {{ addText }} </PrimaryButton>
        </div>
        <div v-if="addRoute" class="ml-4 space-x-2">
            <PrimaryButton @click.prevent="submit">{{ addText }}</PrimaryButton>
        </div>
    </div>
</template>

// resources/js/Components/Tables/TableHeader.tsx
import {Header3} from "@/Components/Typography/Headers";
import PrimaryButton from "@/Components/Buttons/PrimaryButton";

export default function TableHeader({ header, addLink = '', addRoute = '', addText = '', submit }: {
    header: string,
    addLink?: string,
    addRoute?: string,
    addText?: string,
    submit?: CallableFunction,
}) {
    return (
        <div className="sm:flex sm:items-center">
            <div className="sm:flex-auto">
                <Header3>
                    {header}
                </Header3>
            </div>
            <div className="ml-4 space-x-2">
                {addLink && addText ? (
                    <PrimaryButton href={addLink}>
                        {addText}
                    </PrimaryButton>
                ) : null}
                {addRoute ? (
                    <PrimaryButton onClick={submit}>
                        {addText}
                    </PrimaryButton>
                ): null}
            </div>
        </div>
    );
}
