// resources/js/Pages/Settings/Account.tsx
import {Head} from "@inertiajs/react";
import Authenticated from "@/Layouts/Authenticated";
import Settings from "@/Layouts/Settings";
import DeleteAccount from "@/Components/Forms/DeleteAccount";
import {PageProps} from "@/types";

export default function Account({ auth, hasRoles }: PageProps<{ hasRoles: boolean }>) {
    return (
        <>
            <Head title="Account"/>

            <Authenticated user={auth.user}>
                <Settings>
                    <DeleteAccount hasRoles={hasRoles} user={auth.user}/>
                </Settings>
            </Authenticated>
        </>
    );
}

// resources/js/Pages/Settings/Account.vue
<script setup>
import { provide } from '@vue/runtime-core';
import AuthenticatedLayout from '@/Layouts/Authenticated.vue';
import SettingsLayout from '@/Layouts/Settings.vue';
import { Head } from '@inertiajs/vue3';
import DeleteAccount from '@/Components/Forms/DeleteAccount.vue';

const props = defineProps(['hasRoles', 'user']);

provide('user', props.user);
</script>

<template>
    <Head title="Account" />

    <AuthenticatedLayout>
        <SettingsLayout>
            <DeleteAccount :has-roles="hasRoles" />
        </SettingsLayout>
    </AuthenticatedLayout>
</template>
