// resources/js/Pages/Settings/Profile.vue
<script setup>
import { provide } from '@vue/runtime-core';
import AuthenticatedLayout from '@/Layouts/Authenticated.vue';
import SettingsLayout from '@/Layouts/Settings.vue';
import { Head } from '@inertiajs/vue3';
import UpdateProfile from '@/Components/Forms/UpdateProfile.vue';

const props = defineProps(['user']);

provide('user', props.user);
</script>

<template>
    <Head title="Profile" />

    <AuthenticatedLayout>
        <SettingsLayout>
            <UpdateProfile />
        </SettingsLayout>
    </AuthenticatedLayout>
</template>

// resources/js/Pages/Settings/Profile.tsx
import {Head} from "@inertiajs/react";
import Authenticated from "@/Layouts/Authenticated";
import Settings from "@/Layouts/Settings";
import UpdateProfile from "@/Components/Forms/UpdateProfile";
import {PageProps} from "@/types";

export default function Profile({ auth }: PageProps) {
    return (
        <>
            <Head title="Profile"/>

            <Authenticated user={auth.user}>
                <Settings>
                    <UpdateProfile user={auth.user}/>
                </Settings>
            </Authenticated>
        </>
    );
}
