// resources/js/Pages/Settings/Security.vue
<script setup>
import { provide } from 'vue';
import AuthenticatedLayout from '@/Layouts/Authenticated.vue';
import SettingsLayout from '@/Layouts/Settings.vue';
import { Head } from '@inertiajs/vue3';
import UpdatePassword from '@/Components/Forms/UpdatePassword.vue';

const props = defineProps(['user']);

provide('user', props.user);
</script>

<template>
    <Head title="Security" />

    <AuthenticatedLayout>
        <SettingsLayout>
            <UpdatePassword />
        </SettingsLayout>
    </AuthenticatedLayout>
</template>

// resources/js/Pages/Settings/Security.tsx
import {Head} from "@inertiajs/react";
import UpdatePassword from "@/Components/Forms/UpdatePassword";
import Authenticated from "@/Layouts/Authenticated";
import Settings from "@/Layouts/Settings";
import {PageProps} from "@/types";

export default function SecurityPage({ auth }: PageProps) {
    return (
        <>
            <Head title="Security"/>

            <Authenticated user={auth.user}>
                <Settings>
                    <UpdatePassword/>
                </Settings>
            </Authenticated>
        </>
    );
}
