// resources/js/Components/Dropdowns/NotificationDropdownItem.vue
<script setup>
import { Link } from '@inertiajs/vue3';
import { MenuItem } from '@headlessui/vue';
import moment from 'moment';

const props = defineProps({
    notification: Object
});

const readableDate = () => {
    return moment(props.notification.updated_at).fromNow();
}
</script>

<template>
    <MenuItem v-slot="{ active }">
        <Link :href="route('notifications.read', [notification])" :class="[active ? 'bg-gray-100 text-gray-900' : 'text-gray-700', notification.read_at === null ? 'font-bold' : 'font-normal', 'flex flex-col w-full px-4 py-2 text-xs']">
            {{ notification.data.message }}
            <span class="mt-1 text-gray-400">
                {{ readableDate() }}
            </span>
        </Link>
    </MenuItem>
</template>

// resources/js/Components/Dropdowns/NotificationDropdownItem.tsx
import {type ReactElement} from "react";
import {Menu} from "@headlessui/react";
import {Link} from "@inertiajs/react";
import classNames from "@/Utils/classNames";
import moment from "moment";

export default function NotificationDropdownItem({ notification }): ReactElement {
  const readableDate: string = moment(notification.updated_at).fromNow();

  return (
    <Menu.Item>
      {({active}) => (
        <Link
          href={route('notifications.read', notification)}
          className={classNames(
            active ? 'bg-gray-100 text-gray-900' : 'text-gray-700',
            notification.read_at === null ? 'font-bold' : 'font-normal',
            'flex flex-col w-full px-4 py-2 text-xs'
          )}
        >
          {notification.data.message}
          <span className="mt-1 text-gray-400">
            {readableDate}
          </span>
        </Link>
      )}
    </Menu.Item>
  );
}
