// resources/js/Pages/Editor/Drafts/Create.vue
<script setup>
import AdminLayout from '@/Layouts/Admin.vue';
import { Head, useForm } from '@inertiajs/vue3';
import Header3 from '@/Components/Headers/Header3.vue';
import PrimaryButton from '@/Components/Buttons/PrimaryButton.vue';
import InputWithLabel from '@/Components/InputWithLabel.vue';
import AddCoverImage from '@/Components/Forms/AddCoverImage.vue';
import TextEditorWithLabel from '@/Components/TextEditorWithLabel.vue';

const props = defineProps({
    type: String,
    parent_id: String,
});

const form = useForm({
    type: props.type,
    parent_id: props.parent_id,
    name: '',
    image: null,
    summary: null,
    show_me_video_url: null,
});

const setImage = (value) => {
    form.image = value;
}

const submit = () => {
    form.post(route('editor.drafts.store'));
}
</script>

<template>
    <Head title="Create Draft" />

    <AdminLayout>
        <form @submit.prevent="submit" class="w-full py-8 px-4 sm:px-6 lg:px-8">
            <div class="flex items-center justify-between flex-wrap sm:flex-nowrap">
                <div>
                    <Header3> Create Draft </Header3>
                </div>
                <div class="space-x-2">
                    <PrimaryButton> Save </PrimaryButton>
                </div>
            </div>

            <div class="mt-4 bg-white rounded-md shadow">
                <div class="sm:divide-y sm:divide-gray-200">
                    <InputWithLabel label="Name" v-model="form.name" :message="form.errors?.name" />

                    <template v-if="type === 'project'">
                        <AddCoverImage :message="form.errors?.image" @set="setImage($event)" />
                    </template>

                    <template v-if="type === 'goal'">
                        <TextEditorWithLabel label="Summary" v-model="form.summary" :message="form.errors?.summary" />
                        <InputWithLabel label='"Shoe Me" Video' v-model="form.show_me_video_url" :message="form.errors?.show_me_video_url" />
                    </template>
                </div>
            </div>
        </form>
    </AdminLayout>
</template>

// resources/js/Pages/Editor/Drafts/Create.tsx
import {PageProps} from "@/types";
import {Head, useForm} from "@inertiajs/react";
import {FormEventHandler} from "react";
import Admin from "@/Layouts/Admin";
import Container from "@/Components/Container";
import {Header3} from "@/Components/Typography/Headers";
import PrimaryButton from "@/Components/Buttons/PrimaryButton";
import TextInputCombined from "@/Components/Forms/TextInputCombined";
import AddCoverImage from "@/Components/Forms/AddCoverImage";
import TextEditor from "@/Components/Forms/TextEditor";

export default function ({auth, parent_id, type}: PageProps<{ parent_id: number, type: string }>) {
  const {data, setData, post, errors, reset, processing} = useForm({
    type,
    parent_id,
    name: '',
    image: null,
    summary: null,
    show_me_video_url: null,
    content: null,
  });

  const updateCover = (value: File) => {
    setData('image', value);
  };

  const submit: FormEventHandler = (e) => {
    e.preventDefault();

    post(route('editor.drafts.store'));
  }

  return (
    <>
      <Head title="Create Draft"/>

      <Admin user={auth.user}>
        <Container>
          <form onSubmit={submit}>
            <div className="flex items-center justify-between flex-wrap sm:flex-nowrap">
              <Header3>
                Create Draft
              </Header3>
              <PrimaryButton>
                Save
              </PrimaryButton>
            </div>

            <div className="mt-4 bg-white rounded-md shadow">
              <div className="sm:divide-y sm:divide-gray-200">
                <TextInputCombined
                  label="Name"
                  value={data.name}
                  onChange={(e) => setData('name', e.target.value)}
                  message={errors.name}
                />

                {type === 'project' ? (
                  <AddCoverImage
                    name={data.name}
                    errorMessage={errors.image}
                    imagePath={data?.cover_image_path}
                    imageUrl={data?.cover_image_url}
                    onChange={(value) => updateCover(value)}
                  />
                ) : null}

                {type === 'goal' ? (
                  <>
                    <TextEditor/>
                    <TextInputCombined
                      label={`"Show Me" Video`}
                      value={data.show_me_video_url}
                      message={errors.show_me_video_url}
                    />
                  </>
                ) : null}

                {type === 'choice' ? (

                )}
              </div>
            </div>
          </form>
        </Container>
      </Admin>
    </>
  );
}
