// resources/js/Pages/Editor/Drafts/Edit.tsx
import {type Draft, type PageProps} from "@/types";
import {Head, useForm} from "@inertiajs/react";
import Admin from "@/Layouts/Admin";
import Container from "@/Components/Container";
import {Header3} from "@/Components/Typography/Headers";
import PrimaryButtonWithDropDown from "@/Components/Buttons/PrimaryButtonWithDropdown";
import InputLabel from "@/Components/Forms/InputLabel";
import TextInput from "@/Components/Forms/TextInput";
import InputError from "@/Components/Forms/InputError";
import AddCoverImage from "@/Components/Forms/AddCoverImage";
import {useState} from "react";
import PublishModal from "@/Components/Modals/Publish";
import {Dialog} from "@headlessui/react";

export default function DraftEdit({ auth, draft, userCanPublish }: PageProps<{ draft: Draft, userCanPublish: boolean }>) {
  const [confirmDraftPublish, setConfirmDraftPublish] = useState(false);

  const {data, setData, errors, put, processing} = useForm({
    name: draft.name,
    cover_image_path: draft.cover_image_path,
    summary: draft.summary,
    show_me_video_url: draft.show_me_video_url
  });

  const updateCover = (value: File) => {
    setData('cover_image_path', value);
  };

  const save = (): void => {
    put(route('editor.drafts.update', [draft.id]));
  }
  const publish = (): void => {
    put(route('editor.drafts.publish', [draft.id]));
  }
  const notify = (): void => {
    put(route('editor.drafts.notify', [draft.id]));
  }

  const options = [
    { name: 'Publish Draft', icon: 'ArrowUpTrayIcon', show: userCanPublish, emit: () => setConfirmDraftPublish(true) },
    { name: 'Ready for Publish', icon: 'BellAlertIcon', show: !userCanPublish, emit: () => notify() }
  ];

  return (
    <>
      <Head title="Edit Draft"/>

      <Admin user={auth.user}>
        <Container>
          <div className="flex items-center justify-between flex-wrap sm:flex-nowrap">
            <Header3>
              Edit Draft: {draft.name}
            </Header3>
            <div className="space-x-2">
              <PrimaryButtonWithDropDown
                action="Save Draft"
                save={save}
                options={options}
              />
            </div>
          </div>

          <div className="mt-4 bg-white rounded-md shadow">
            <form className="sm:divide-y sm:divide-gray-200">
              <div className="px-6 sm:grid sm:grid-cols-5 sm:gap-4 sm:items-start sm:py-4">
                <InputLabel label="Draft name" className="sm:mt-px sm:pt-2"/>
                <div className="mt-1 sm:mt-0 sm:col-span-4">
                  <TextInput
                    value={data.name}
                    className="block w-full"
                    isFocused={true}
                    onChange={(e) => {
                      setData('name', e.target.value)
                    }}
                  />
                  <InputError message={errors.name}/>
                </div>
              </div>

              {draft.draftable_type === 'project' ? (
                <AddCoverImage
                  name={data.cover_image_path}
                  errorMessage={errors.cover_image_path}
                  imagePath={draft.cover_image_path}
                  imageUrl={draft.cover_image_url}
                  onChange={(value) => updateCover(value)}
                />
              ) : null}

              {draft.draftable_type === 'goal' ? (
                // TextEditor

                <div className="px-6 sm:grid sm:grid-cols-5 sm:gap-4 sm:items-start sm:py-4">
                  <InputLabel label={`"Show Me" Video`} className="sm:mt-px sm:pt-2"/>
                  <div className="mt-1 sm:mt-0 sm:col-span-4">
                    <TextInput
                      value={data.show_me_video_url}
                      className="block w-full"
                      onChange={(e) => {
                        setData('show_me_video_url', e.target.value)
                      }}
                    />
                    <InputError message={errors.show_me_video_url}/>
                  </div>
                </div>
              ) : null}

              {draft.draftable_type === 'choice' ? (
                "add choice content"
              ) : null}
            </form>
          </div>
        </Container>
      </Admin>

      <PublishModal open={confirmDraftPublish} setOpen={setConfirmDraftPublish} publish={publish}>
        <Dialog.Title as="h3" className="text-lg leading-6 font-medium text-gray-900">
          Publish Draft
        </Dialog.Title>
        <div className="mt-2">
          <p className="text-sm text-gray-500">
            Hooray! You&apos;re ready to publish this draft. Please click
            the publish button to confirm this action.
          </p>
        </div>
      </PublishModal>
    </>
  );
}

// resources/js/Pages/Editor/Drafts/Edit.vue
<script setup>
import { ref, watch } from 'vue';
import { DialogTitle } from '@headlessui/vue';
import { ArrowUpTrayIcon, BellAlertIcon } from '@heroicons/vue/24/solid';
import { Head, useForm } from '@inertiajs/vue3';
import AdminLayout from '@/Layouts/Admin.vue';
import InputWithLabel from '@/Components/InputWithLabel.vue';
import TextEditorWithLabel from '@/Components/TextEditorWithLabel.vue';
import PrimaryButtonWithDropdown from '@/Components/Buttons/PrimaryButtonWithDropdown.vue';
import PublishModal from '@/Components/PublishModal.vue';
import Header3 from '@/Components/Headers/Header3.vue';

const props = defineProps({
    draft: Object,
    userCanPublish: Boolean
});
const open = ref(false);

const confirm = () => {
    open.value = true;
}
const close = () => {
    open.value =  false;
}

const form = useForm({
    ...props.draft
});
const save = () => {
    form.put(route('editor.drafts.update', [props.draft.id]));
}
const publish = () => {
    form.put(route('editor.drafts.publish', [props.draft.id]));
}
const notify = () => {
    form.post(route('editor.drafts.notify', [props.draft.id]));
}

const options = [
    { name: 'Publish Draft', icon: ArrowUpTrayIcon, show: props.userCanPublish, action: 'publish' },
    { name: 'Ready for Publish', icon: BellAlertIcon, show: !props.userCanPublish, action: 'notify' }
];
</script>

<template>
    <Head title="Draft" />

    <AdminLayout>
        <div class="w-full py-8 px-4 sm:px-6 lg:px-8">
            <div class="flex items-center justify-between flex-wrap sm:flex-nowrap">
                <div>
                    <Header3> Draft: {{ form.name }} </Header3>
                </div>
                <div class="space-x-2">
                    <PrimaryButtonWithDropdown action="Save Draft" @save="save" @publish="confirm" @notify="notify" :options="options" />
                </div>
            </div>
            
            <div class="mt-4 bg-white rounded-md shadow">
                <form @submit.prevent="submit" class="sm:divide-y sm:divide-gray-200">
                    <InputWithLabel label="Name" v-model="form.name" :message="form.errors?.name" />

                    <TextEditorWithLabel v-if="['goal','choice'].includes(draft.draftable_type)" label="Summary" v-model="form.summary" :message="form.errors?.summary" />

                    <TextEditorWithLabel v-if="draft.draftable_type === 'choice'" label="Instructions" v-model="form.instructions" :message="form.errors?.instructions" />

                    <TextEditorWithLabel v-if="draft.draftable_type === 'choice'" label="Resources" v-model="form.resources" :message="form.errors?.resources" />

                    <TextEditorWithLabel v-if="draft.draftable_type === 'choice'" label="Review" v-model="form.review" :message="form.errors?.review" />

                    <TextEditorWithLabel v-if="draft.draftable_type === 'choice'" label="Exercises" v-model="form.exercises" :message="form.errors?.exercises" />
                </form>
            </div>
        </div>

        <Teleport to="body">
            <PublishModal :open="open" @close="close" @publish="publish">
                <DialogTitle as="h3" class="text-lg leading-6 font-medium text-gray-900"> Publish Draft </DialogTitle>
                <div class="mt-2">
                    <p class="text-sm text-gray-500">Hooray! You're ready to publish this draft. Please click the publish button to confirm this action.</p>
                </div>
            </PublishModal>
        </Teleport>
    </AdminLayout>
</template>
