// resources/js/Components/Lists/ExpandableChoiceItem.vue
<script setup>
import { ref } from 'vue';
import { MinusIcon, PlusIcon } from '@heroicons/vue/24/outline';
import ResourceListItem from '@/Components/Lists/ResourceListItemPublic.vue';
import Header5 from '@/Components/Headers/Header5.vue';

defineProps({
    choice: Object
});

const expanded = ref(true);
const showSummary = ref(false);
const showExercises = ref(false);

const listStyleAlpha = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z'];
</script>

<template>
    <li>
        <div @click="expanded = !expanded" class="flex items-center justify-between text-stone-400 text-2xl cursor-pointer">
            <div class="flex items-center">
                <div class="inline-flex items-center flex-shrink-0 justify-center w-10 h-10 bg-stone-400 text-white font-display font-medium rounded-full">{{ listStyleAlpha[choice.order - 1] }}</div>
                <h4 class="ml-3 font-display font-medium">{{ choice.name }}</h4>
            </div>
            <div class="flex items-center">
                <MinusIcon v-if="expanded" class="h-8 w-8 flex-shrink-0" />
                <PlusIcon v-if="! expanded" class="h-8 w-8 flex-shrink-0" />
            </div>
        </div>
        <div v-show="expanded" class="py-8 prose max-w-none space-y-6">
            <template v-for="item in choice.content" :key="item.id">
                <div v-if="item.type === 'summary'">
                    <button @click="showSummary = ! showSummary" class="text-stone-500 font-medium hover:underline">Summary</button>
                    <div v-show="showSummary" v-html="item.data" />
                </div>
                <div v-else-if="item.type === 'resources'">
                    <Header5>Resources</Header5>
                    <ol>
                        <ResourceListItem v-for="(resource, index) in item.data" :key="index" :resource="resource" />
                    </ol>
                </div>
                <div v-else-if="item.type === 'exercises'">
                    <button @click="showExercises = ! showExercises" class="text-stone-500 font-medium hover:underline">Exercises</button>
                    <div v-show="showExercises" v-html="item.data" />
                </div>
                <div v-else-if="item.type === 'header'">
                    <Header5>{item.data}</Header5>
                </div>
                <div v-else v-html="item.data" />
            </template>
        </div>
    </li>
</template>

// resources/js/Components/Lists/ExpandableChoiceItem.tsx
import {type ReactElement, useState} from "react";
import {type Choice, ChoiceContentTypes, Resource} from "@/types";
import {MinusIcon, PlusIcon} from "@heroicons/react/24/solid";
import {Header5} from "@/Components/Typography/Headers";
import ResourceListItem from "@/Components/Lists/ResourceListItem";

const listStyleAlpha = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z'];

export default function ExpandableChoiceItem({ choice }: { choice: Choice }): ReactElement {
  const [expanded, setExpanded] = useState<boolean>(true);
  const [showSummary, setShowSummary] = useState<boolean>(false);
  const [showExercises, setShowExercises] = useState<boolean>(false);

  return (
    <li>
      <div onClick={() => { setExpanded(!expanded) }} className="flex items-center justify-between text-stone-400 text-2xl cursor-pointer">
        <div className="flex items-center">
          <div className="inline-flex items-center flex-shrink-0 justify-center w-10 h-10 bg-stone-400 text-white font-display font-medium rounded-full">
            {listStyleAlpha[choice.order - 1]}
          </div>
          <h4 className="ml-3 font-display font-medium">
            {choice.name}
          </h4>
        </div>
        <div className="flex items-center">
          {expanded ? (
            <MinusIcon className="h-8 w-8 flex-shrink-0"/>
          ) : (
            <PlusIcon className="h-8 w-8 flex-shrink-0"/>
          )}
        </div>
      </div>

      {expanded && (
        <div className="py-8 prose max-w-none space-y-6">
          {choice.content.map((item) => {
            if (item.type === ChoiceContentTypes.SUMMARY) {
              return <>
                <button
                  onClick={() => setShowSummary(!showSummary)}
                  className="text-stone-500 font-medium hover:underline"
                >
                  Summary
                </button>
                {showSummary && (
                  <div dangerouslySetInnerHTML={{__html: item.data}}/>
                )}
              </>
            } else if (item.type === ChoiceContentTypes.RESOURCES) {
              return <>
                <Header5>
                  Resources
                </Header5>
                <ol>
                  {item.data.map((resource: Resource, index: number) => (
                    <ResourceListItem key={index} resource={resource}/>
                  ))}
                </ol>
              </>
            } else if (item.type === ChoiceContentTypes.EXERCISES) {
              return <>
                <button
                  onClick={() => setShowExercises(!showExercises)}
                  className="text-stone-500 font-medium hover:underline"
                >
                  Exercises
                </button>
                {showExercises && (
                  <div dangerouslySetInnerHTML={{__html: item.data}}/>
                )}
              </>
            } else if (item.type === ChoiceContentTypes.HEADER) {
              return <Header5>{item.data}</Header5>
            } else {
              return <div dangerouslySetInnerHTML={{ __html: item.data }}/>
            }
          })}
        </div>
      )}
    </li>
  );
}
