// resources/js/Components/Lists/ResourceListItem.vue
<script setup>
import { ref } from 'vue';
import { useForm } from '@inertiajs/vue3';
import { DocumentTextIcon, VideoCameraIcon } from '@heroicons/vue/24/outline'
import { XMarkIcon } from '@heroicons/vue/24/solid';
import PrimaryTextButton from '@/Components/Buttons/PrimaryTextButton.vue';
import BreezeInput from '@/Components/Input.vue';
import BreezeLabel from '@/Components/Label.vue';
import PrimaryButton from '@/Components/Buttons/PrimaryButton.vue';
import SecondaryButton from '@/Components/Buttons/SecondaryButton.vue';

const props = defineProps(['resource']);

const emit = defineEmits(['update'])

const view = ref('show');

const form = useForm({
    ...props.resource
});

const submit = () => {
    form.put(route('editor.resources.update'), {
        preserveScroll: true,
        preserveState: true,
    });
}

const saveResource = () => {
    submit();
    view.value = "show";
}
</script>

<template>
    <li class="flex items-center justify-between py-3 pl-3 pr-4 text-sm">
        <div v-if="view ==='show'" class="flex w-full flex-col">
            <span class="ml-2 truncate">{{ form.description }}</span>
            <ul class="mt-3 ml-4 space-y-1">
                <li v-for="link in form.links" :key="link" class="flex">
                    <DocumentTextIcon v-if="link.type === 'document'" class="h-5 w-auto flex-shrink-0 text-gray-400" aria-hidden="true" />
                    <VideoCameraIcon v-else-if="link.type === 'video'" class="h-5 w-auto flex-shrink-0 text-gray-400" aria-hidden="true" />
                    <a :href="link.link" class="pl-2">{{ link.text }}</a>
                </li>
            </ul>
        </div>
        <div v-if="view ==='edit'" class="flex w-full items-center">
            <form class="w-full flex flex-col items-center">
                <div class="w-full flex items-center border border-purple-200 rounded-md focus-within:border-purple-300">
                    <input type="text" v-model="resource.description" placeholder="Description" class="flex-1 border-none text-sm rounded-l-md focus:ring-transparent">
                    <div class="flex items-center ml-2 mr-1 space-x-2">
                        <PrimaryButton @click.prevent="saveResource" class="px-2 py-0.5 text-xs rounded bg-purple-200 text-purple-700 hover:bg-purple-300" :disabled="resource.links.length < 1">Save</PrimaryButton>
                        <button type="button" class="rounded hover:bg-purple-100">
                            <XMarkIcon class="w-5 h-5 text-purple-700" @click.prevent="view = 'show'" />
                        </button>
                    </div>
                </div>
                <div class="w-full pl-4 mt-1 space-y-1">
                    <div v-for="(link, key) in resource.links" :key="key" class="flex items-center border border-purple-200 rounded-md focus-within:border-purple-300">
                        <input type="text" v-model="link.text" placeholder="Name" class="flex-1 border-none text-sm rounded-l-md focus:ring-transparent" autofocus>
                        <input type="text" v-model="link.link" placeholder="External URL" class="flex-1 border-none text-sm focus:ring-transparent">
                        <select id="location" v-model="link.type" name="location" class="border-none py-2 pl-3 pr-10 text-sm focus:ring-transparent">
                            <option value="document">Document</option>
                            <option value="video">Video</option>
                        </select>
                        <div class="flex items-center ml-2 mr-1">
                            <button type="button" class="rounded hover:bg-purple-100">
                                <XMarkIcon class="w-5 h-5 text-purple-700" @click.prevent="remove(key)" />
                            </button>
                        </div>
                    </div>
                    <PrimaryButton @click.prevent="addLink()" class="px-2 py-0.5 text-xs rounded bg-purple-200 text-purple-700 hover:bg-purple-300">+ Add resource link</PrimaryButton>
                </div>
            </form>
        </div>
        <div v-if="view === 'show'" class="ml-4 flex-shrink-0">
            <PrimaryTextButton @click.prevent="view = 'edit'">Edit</PrimaryTextButton>
        </div>
    </li>
</template>

// resources/js/Components/Lists/ResourceListItem.tsx
import {FormEventHandler, ReactElement, useState} from "react";
import {useForm} from "@inertiajs/react";
import {DocumentTextIcon, VideoCameraIcon} from "@heroicons/react/24/outline";
import Anchor from "@/Components/Anchor";
import PrimaryButton from "@/Components/Buttons/PrimaryButton";
import {XMarkIcon} from "@heroicons/react/24/solid";
import PrimaryTextButton from "@/Components/Buttons/PrimaryTextButton";

export default function ({ resource }): ReactElement {
  const [view, setView] = useState('show');

  const {data, setData, errors, put, processing, reset} = useForm({
    ...resource,
  });

  const submit = () => {
    put(route('editor.resources.update'), {
      preserveScroll: true,
      preserveState: true,
    });
  }

  const saveResource: FormEventHandler = (e) => {
    e.preventDefault();

    submit();
    setView('show');
  }

  const addLink = () => { }

  return (
    <li className="flex items-center justify-between py-3 pl-3 pr-4 text-sm">
      {view === 'show' ? (
        <>
          <div className="flex w-full flex-col">
            <span className="ml-2 truncate">{data.description}</span>
            <ul className="mt-3 ml-4 space-y-1">
              {data.links.map((link, linkIdx) => (
                <li className="flex" key={linkIdx}>
                  {link.type === 'document' && <DocumentTextIcon className="h-5 w-auto flex-shrink-0 text-gray-400" aria-hidden={true}/>}
                  {link.type === 'video' && <VideoCameraIcon className="h-5 w-auto flex-shrink-0 text-gray-400" aria-hidden={true}/>}
                  <Anchor href={link.link} className="pl-2">
                    {link.text}
                  </Anchor>
                </li>
              ))}
            </ul>
          </div>
          <div className="ml-4 flex-shrink-0">
            <PrimaryTextButton onClick={() => setView('edit')}>
              Edit
            </PrimaryTextButton>
          </div>
        </>
      ) : (
        <div className="flex w-full items-center">
          <form className="w-full flex flex-col items-center">
            <div className="w-full flex items-center border border-purple-200 rounded-md focus-within:border-purple-300">
              <input
                type="text"
                value={data.description}
                placeholder="Description"
                className="flex-1 border-none text-sm rounded-l-md focus:ring-transparent"
              />
              <div className="flex items-center ml-2 mr-1 space-x-2">
                <PrimaryButton
                  onClick={saveResource}
                  className="px-2 py-0.5 text-xs rounded bg-purple-200 text-purple-700 hover:bg-purple-300"
                  disabled={data.links.length < 1}
                >
                  Save
                </PrimaryButton>
                <button type="button" className="rounded hover:bg-purple-100">
                  <XMarkIcon onClick={() => setView('show')} className="w-5 h-5 text-purple-700"/>
                </button>
              </div>
            </div>
          </form>
          <div className="w-full pl-4 mt-1 space-y-1">
            {resource.links.map((link, linkIdx) => (
              <>
              <div key={linkIdx} className="flex items-center border border-purple-200 rounded-md focus-within:border-purple-300">
                <input
                  type="text"
                  value={link.text}
                  placeholder="Name"
                  className="flex-1 border-none text-sm rounded-l-md focus:ring-transparent"
                />
                <input
                  type="text"
                  value={link.link}
                  placeholder="External URL"
                  className="flex-1 border-none text-sm focus:ring-transparent"
                />
                <select
                  value={link.type}
                  className="border-none py-2 pl-3 pr-10 text-sm focus:ring-transparent"
                >
                  <option value="document">Document</option>
                  <option value="video">Video</option>
                </select>
                <div className="flex items-center ml-2 mr-1">
                  <button type="button" className="rounded hover:bg-purple-100">
                    <XMarkIcon className="h-5 w-5 text-purple-700"/>
                  </button>
                </div>
              </div>
                <PrimaryButton
                  onClick={addLink}
                  className="px-2 py-0.5 text-xs rounded bg-purple-200 text-purple-700 hover:bg-purple-300"
                >
                  &#43; Add resource link
                </PrimaryButton>
              </>
            ))}
          </div>
        </div>
      )}
    </li>
  );
}
