// resources/js/Components/Lists/ResourceListItemPublic.vue
<script setup>
import ResourceLink from '@/Components/Lists/ResourceLink.vue';

defineProps(['resource']);
</script>

<template>
    <li>
        <span> {{ resource.description }} </span>
        <ul class="list-none">
            <ResourceLink v-for="(item, index) in resource.links" :key="index" :resource="item" />
        </ul>
    </li>
</template>

// resources/js/Components/Lists/ResourceListItemPublic.tsx
import ResourceLink from "@/Components/Lists/ResourceLink";

export default function ResourceListItemPublic({ resource }) {
    return (
        <li>
            <span>
                {resource.description}
            </span>
            <ul className="list-none">
                {resource.links.map((item, idx) => (
                    <ResourceLink key={idx} resource={item}/>
                ))}
            </ul>
        </li>
    );
}
