// resources/js/Components/Lists/ResourceLink.vue
<script setup>
import { DocumentTextIcon, StarIcon, VideoCameraIcon } from '@heroicons/vue/24/outline';

defineProps(['resource']);
</script>

<template>
    <li class="flex items-center space-x-2">
        <StarIcon class="h-5 w-5 flex-shrink-0" />
        <DocumentTextIcon class="h-5 w-5 flex-shrink-0" v-if="resource.type === 'document'" />
        <VideoCameraIcon class="h-5 w-5 flex-shrink-0" v-else-if="resource.type === 'video'" />
        <a :href="resource.link" target="_blank" rel="nofollow noopener noreferrer"> {{ resource.text }} </a>
    </li>
</template>

// resources/js/Components/Lists/ResourceLink.tsx
import {DocumentTextIcon, StarIcon, VideoCameraIcon} from "@heroicons/react/24/outline";

export default function ResourceLink({ resource }) {
    return (
        <li className="flex items-center space-x-2">
            <StarIcon className="h-5 w-5 flex-shrink-0"/>
            {resource.type === 'document' && <DocumentTextIcon className="h-5 w-5 flex-shrink-0"/>}
            {resource.type === 'video' && <VideoCameraIcon className="h-5 w-5 flex-shrink-0"/>}
            <a href={resource.link} target="_blank" rel="nofollow noopener noreferrer">
                {resource.text}
            </a>
        </li>
    );
}
