// resources/js/Pages/Editor/Drafts/Create.tsx
import {Head, useForm} from "@inertiajs/react";
import {FormEventHandler} from "react";
import Admin from "@/Layouts/Admin";
import Container from "@/Components/Container";
import {Header3} from "@/Components/Typography/Headers";
import PrimaryButton from "@/Components/Buttons/PrimaryButton";
import AddCoverImage from "@/Components/Forms/AddCoverImage";
import TextEditor from "@/Components/Forms/TextEditor";
import InputLabel from "@/Components/Forms/InputLabel";
import TextInput from "@/Components/Forms/TextInput";
import InputError from "@/Components/Forms/InputError";
import ChoiceContentForm from "@/Components/Forms/Choices/ChoiceContentForm";
import {type Draft, type PageProps, type Resource} from "@/types";

export default function DraftCreate({auth, parent_id, type}: PageProps<{ parent_id: number, type: string }>) {
  const {data, setData, post, errors, reset, processing} = useForm<Draft>({
    type,
    parent_id,
    name: '',
    image: {},
    summary: null,
    show_me_video_url: null,
    content: [],
  });

  const updateCover = (value: File) => {
    setData('image', value);
  };

  const updateProperty = (index: number, value: string|Resource[]): void => {
    let { content } = data;
    content[index].data = value;

    setData({
      ...data,
      content,
    });
  }

  const addProperty = (type: string): void => {
    type === 'resources'
      ? setData({
        ...data,
        content: [
          ...data.content,
          {'type': type, 'data': []}
        ]
      })
      : setData({
        ...data,
        content: [
          ...data.content,
          { 'type': type, 'data': "" }
        ]
      });
  }

  const handleDelete = (index: number): void => {
    let selectedChoice = data;
    selectedChoice.content.splice(index, 1);
    setData({
      ...selectedChoice,
    });
  }

  const submit: FormEventHandler = (e) => {
    e.preventDefault();
    if (data.image !== typeof File) {
      delete data.image;
    }
    post(route('editor.drafts.store'));
  }

  return (
    <>
      <Head title="Create Draft"/>

      <Admin user={auth.user}>
        <Container>
          <div className="flex items-center justify-between flex-wrap sm:flex-nowrap">
            <Header3>
              Create Draft
            </Header3>
            <PrimaryButton onClick={submit} disabled={processing}>
              Save
            </PrimaryButton>
          </div>

          <div className="mt-4 bg-white rounded-md shadow">
            <form className="sm:divide-y sm:divide-gray-200">
              <div className="px-6 sm:grid sm:grid-cols-8 sm:gap-4 sm:items-start sm:py-4">
                <InputLabel label="Name" className="sm:mt-px sm:pt-2"/>
                <div className="mt-1 sm:mt-0 sm:col-span-7">
                  <TextInput
                    value={data.name}
                    className="block w-full"
                    isFocused={true}
                    onChange={(e) => {
                      setData('name', e.target.value)
                    }}
                  />
                  <InputError message={errors.name}/>
                </div>
              </div>

              {type === 'project' ? (
                <AddCoverImage
                  name={data.name}
                  errorMessage={errors.image}
                  imagePath={data?.cover_image_path}
                  imageUrl={data?.cover_image_url}
                  onChange={(value) => updateCover(value)}
                />
              ) : null}

              {type === 'goal' ? (
                <>
                  <div className="px-6 sm:grid sm:grid-cols-8 sm:gap-4 sm:items-start sm:py-4">
                    <InputLabel label="Summary" className="sm:mt-px sm:pt-2"/>
                    <div className="mt-1 sm:mt-0 sm:col-span-7">
                      <TextEditor
                        value={data.summary}
                      />
                      <InputError message={errors.summary}/>
                    </div>
                  </div>

                  <div className="px-6 sm:grid sm:grid-cols-8 sm:gap-4 sm:items-start sm:py-4">
                    <InputLabel label={`"Show Me" Video`} className="sm:mt-px sm:pt-2"/>
                    <div className="mt-1 sm:mt-0 sm:col-span-7">
                      <TextInput
                        value={data.show_me_video_url}
                        className="block w-full"
                        onChange={(e) => {
                          setData('show_me_video_url', e.target.value)
                        }}
                      />
                      <InputError message={errors.show_me_video_url}/>
                    </div>
                  </div>
                </>
              ) : null}

              {type === 'choice' ? (
                <ChoiceContentForm
                  add={(type) => addProperty(type)}
                  content={data.content}
                  remove={(index) => handleDelete(index)}
                  update={(index, value) => updateProperty(index, value)}
                />
              ) : null}
            </form>
          </div>
        </Container>
      </Admin>
    </>
  );
}

// resources/js/Pages/Editor/Content/Choices/Create.vue
<script setup>
import { ref } from 'vue';
import { Head, useForm } from '@inertiajs/vue3';
import AdminLayout from '@/Layouts/Admin.vue';
import BreezeInput from '@/Components/Input.vue';
import BreezeInputError from '@/Components/InputError.vue';
import BreezeLabel from '@/Components/Label.vue';
import PrimaryButton from '@/Components/Buttons/PrimaryButton.vue';
import SecondaryButton from '@/Components/Buttons/SecondaryButton.vue';
import Header3 from '@/Components/Headers/Header3.vue';
import Summary from '@/Components/Forms/Choices/Summary.vue';
import AddSummaryButton from '@/Components/Buttons/Choices/AddSummaryButton.vue';
import TextBlock from '@/Components/Forms/Choices/TextBlock.vue';
import AddTextBlockButton from '@/Components/Buttons/Choices/AddTextBlockButton.vue';
import Images from '@/Components/Forms/Choices/Images.vue';
import ResourceList from '@/Components/Forms/Choices/ResourceList.vue';
import AddResourceListButton from '@/Components/Buttons/Choices/AddResourceListButton.vue';
import Header from '@/Components/Forms/Choices/Header.vue';
import AddHeaderButton from '@/Components/Buttons/Choices/AddHeaderButton.vue';
import Exercises from '@/Components/Forms/Choices/Exercises.vue';
import AddExercisesButton from '@/Components/Buttons/Choices/AddExercisesButton.vue';
import QUIKLinks from '@/Components/Forms/Choices/QUIKLinks.vue';
import AddQuikLinksButton from '@/Components/Buttons/Choices/AddQuikLinksButton.vue';

const props = defineProps({
    goal: Object,
});

const choice = useForm({
    name: '',
    goal_id: props.goal.id,
    images: [],
    content: [],
});

const hasSummary = ref(false);
const hasExercises = ref(false);

const addProperty = (type) => {
    type === 'resources' ? choice.content.push({ 'type': type, 'data': [] }) : choice.content.push({ 'type': type, 'data': "" });

    if (type === 'summary') {
        hasSummary.value = true;
    }
    if (type === 'exercises') {
        hasExercises.value = true;
    }
}

const updateProperty = (index, data) => {
    choice.content[index].data = data;
}

const updateImages = (data) => {
    choice.images = data;
}

const deleteProperty = (index) => {
    if (choice.content[index].type === 'summary') {
        hasSummary.value = false;
    }
    if (choice.content[index].type === 'exercises') {
        hasExercises.value = false;
    }

    choice.content.splice(index, 1);
}

const submit = () => {
    choice.post(route('editor.choices.store'));
}
</script>

<template>
    <Head title="Admin - Create Choice" />

    <AdminLayout>
        <div class="w-full py-8 px-4 sm:px-6 lg:px-8">
            <Header3> Create Choice </Header3>
            <div class="mt-4 bg-white rounded-md shadow">
                <form @submit.prevent="submit" class="divide-y divide-gray-200">
                    <div class="divide-y divide-gray-200">
                        <div>
                            <div class="divide-y divide-gray-200">
                                <div class="px-6 py-4 sm:grid sm:grid-cols-8 sm:gap-4 sm:items-center sm:pt-4">
                                    <BreezeLabel for="name" value="Name" />
                                    <div class="mt-1 sm:mt-0 sm:col-span-7">
                                        <BreezeInput type="text" v-model="choice.name" id="name" class="block w-full" />
                                        <BreezeInputError class="mt-1" :message="choice.errors?.name" />
                                    </div>
                                </div>
                                <div class="px-6 py-4 sm:grid sm:grid-cols-8 sm:gap-4 sm:items-start sm:pt-4">
                                    <BreezeLabel for="name" value="Content" class="sm:mt-px sm:pt-1" />
                                    <div class="mt-1 space-y-4 sm:mt-0 sm:col-span-7">
                                        <template v-for="(item, index) in choice.content" :key="index">
                                            <Summary v-if="item.type === 'summary'" @delete="deleteProperty(index)" @update="updateProperty(index, $event)" :item="item" />
                                            <TextBlock v-else-if="item.type === 'text'" @delete="deleteProperty(index)" @update="updateProperty(index, $event)" :item="item" />
                                            <ResourceList v-if="item.type === 'resources'" @delete="deleteProperty(index)" @update="updateProperty(index, $event)" :item="item" />
                                            <Header v-else-if="item.type === 'header'" @delete="deleteProperty(index)" @update="updateProperty(index, $event)" :item="item" />
                                            <Exercises v-else-if="item.type === 'exercises'" @delete="deleteProperty(index)" @update="updateProperty(index, $event)" :item="item" />
                                            <QUIKLinks v-else-if="item.type === 'quiklinks'" @delete="deleteProperty(index)" @update="updateProperty(index, $event)" :item="item" />
                                        </template>
                                        <div class="space-x-2">
                                            <AddSummaryButton v-if="! hasSummary" @click.prevent="addProperty('summary')" />
                                            <AddTextBlockButton @click.prevent="addProperty('text')" />
                                            <AddResourceListButton @click.prevent="addProperty('resources')" />
                                            <AddHeaderButton @click.prevent="addProperty('header')" />
                                            <AddExercisesButton v-if="! hasExercises" @click.prevent="addProperty('exercises')" />
                                            <AddQuikLinksButton @click.prevent="addProperty('quiklinks')" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="px-6 py-4">
                        <div class="flex justify-end">
                            <SecondaryButton :href="route('editor.goals.show', [goal.id])" as="link">Cancel</SecondaryButton>
                            <PrimaryButton type="submit" class="ml-3">Save</PrimaryButton>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </AdminLayout>
</template>
