// resources/js/Pages/Editor/Content/Goals/Show.tsx
import { type FormEventHandler, type ReactElement, useState } from 'react'
import { Head, Link, router } from '@inertiajs/react'
import { Dialog } from '@headlessui/react'
import Admin from '@/Layouts/Admin'
import Container from '@/Components/Container'
import { Header3 } from '@/Components/Typography/Headers'
import SecondaryButtonWithDropdown from '@/Components/Buttons/SecondaryButtonWithDropdown'
import TableHeader from '@/Components/Tables/TableHeader'
import Table from '@/Components/Tables/Table'
import TableHead from '@/Components/Tables/TableHead'
import TableBody from '@/Components/Tables/TableBody'
import Prose from '@/Components/Prose'
import DangerModal from '@/Components/Modals/Danger'
import ExpandableStackedListItem from '@/Components/Lists/ExpandableStackedListItem'
import { type Goal, type PageProps } from '@/types'

export default function GoalShow ({ auth, goal }: PageProps<{
  goal: Goal
}>): ReactElement {
  const [confirmGoalArchive, setConfirmGoalArchive] = useState(false)

  const archive: FormEventHandler = (e) => {
    e.preventDefault()

    router.delete(route('editor.goals.destroy', [goal.id]))
  }

  const sortedChoices = goal.choices.sort((a, b) => a.order - b.order)

  const actions = [
    [
      { name: 'Edit', as: 'link', icon: 'PencilSquareIcon', href: route('editor.goals.edit', [goal.id]) },
      { name: 'Add Assignment', as: 'link', icon: 'PlusCircleIcon', href: `${route('admin.assignments.create')}?assignable_id=${goal.id}&assignable_type=goal` },
      { name: 'Preview Goal', as: 'link', icon: 'WindowIcon', href: route('editor.goals.preview', [goal.id]), target: '_blank' }
    ],
    [
      { name: 'Archive', as: 'emitter', icon: 'ArchiveBoxIcon', emit: () => { setConfirmGoalArchive(true) } }
    ]
  ]

  const draftCells = {
    name: 'Name',
    user: 'Author',
    updated_at: 'Last Updated'
  }
  const tableActions = {
    view: true,
    edit: true
  }

  return (
    <>
      <Head title={`Admin - Goals - ${goal.name}`}/>

      <Admin user={auth.user}>
        <Container>
          <div className="-ml-4 -mt-2 flex items-center justify-between flex-wrap sm:flex-nowrap">
            <div className="ml-4 mt-2">
              <Header3>
                Goal Details {goal.name}
              </Header3>
            </div>
            <div className="ml-4">
              <SecondaryButtonWithDropdown
                buttonText="Options"
                actions={actions}
              />
            </div>
          </div>

          <div className="mt-4 bg-white shadow overflow-hidden sm:rounded-lg">
            <dl className="sm:divide-y sm:divide-gray-200">
              <div className="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                <dt className="text-sm font-medium text-gray-500">
                  Name
                </dt>
                <dd className="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                  {goal.name}
                </dd>
              </div>
              <div className="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                <dt className="text-sm font-medium text-gray-500">
                  Summary
                </dt>
                <dd className="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                  <Prose html={goal.summary}/>
                </dd>
              </div>
              <div className="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                <dt className="text-sm font-medium text-gray-500">
                  &apos;Show Me&apos; Video
                </dt>
                <dd className="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                  {goal.show_me_video_url}
                </dd>
              </div>
              <div className="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                <dt className="text-sm font-medium text-gray-500">
                  Belongs to
                </dt>
                <dd className="mt-1 text-sm font-bold text-gray-900 sm:mt-0 sm:col-span-2">
                  <Link className="hover:text-gray-600" href={route('editor.projects.show', [goal.project_id])}>
                    {goal.project.name}
                  </Link>
                </dd>
              </div>
            </dl>
          </div>

          <div className="mt-12">
            <TableHeader
              header="Choices"
              addText="Add choice"
              addRoute={route('editor.drafts.create', { type: 'choice', parent_id: goal.id })}
            />
            <ul className="mt-3 space-y-2">
              {sortedChoices.map((choice) => <ExpandableStackedListItem item={choice} key={choice.id}/>)}
            </ul>
          </div>

          {goal.child_drafts.length > 0 ? (
            <div className="mt-12">
              <TableHeader header="Choice Drafts"/>
              <Table className="mt-2">
                <TableHead cells={draftCells} actions={true}/>
                <TableBody
                  cells={draftCells}
                  rows={goal.child_drafts}
                  routeType="editor.drafts"
                  actions={tableActions}
                />
              </Table>
            </div>
          ) : null}
        </Container>
      </Admin>

      <DangerModal dangerButtonText="Archive" destroy={archive} open={confirmGoalArchive} setOpen={setConfirmGoalArchive}>
        <Dialog.Title as="h3" className="text-lg font-medium leading-6 text-gray-900">
          Archive Goal
        </Dialog.Title>
        <div className="mt-2">
          <p className="text-sm text-gray-500">
            Are you sure you want to archive {goal.name}?
          </p>
        </div>
      </DangerModal>
    </>
  )
}

// resources/js/Pages/Editor/Content/Choices/Show.vue
<script setup>
import { ref } from 'vue';
import { DialogTitle } from '@headlessui/vue';
import { DocumentPlusIcon, EyeIcon, PencilSquareIcon, TrashIcon } from '@heroicons/vue/24/outline';
import { ArchiveBoxIcon, PencilSquareIcon as PencilSquareIconSolid, PlusCircleIcon } from '@heroicons/vue/24/solid';
import { router } from '@inertiajs/vue3';
import { Head, Link } from '@inertiajs/vue3';
import AdminLayout from '@/Layouts/Admin.vue';
import SecondaryButton from '@/Components/Buttons/SecondaryButton.vue';
import Danger from '@/Components/Modals/DangerModal.vue';
import SecondaryButtonWithDropdown from '@/Components/Buttons/SecondaryButtonWithDropdown.vue';
import Header3 from '@/Components/Headers/Header3.vue';

const props = defineProps({
    choice: Object,
});

const open = ref(false);

const close = () => {
    open.value = false;
}
const destroy = () => {
    router.delete(route('editor.choices.destroy', [props.choice.id]));
}

const actions = [
    [
        { name: 'Edit', as: 'link', icon: PencilSquareIconSolid, href: route('editor.choices.edit', [props.choice.id]) },
        { name: 'Add Assignment', as: 'link', icon: PlusCircleIcon, href: `${route('admin.assignments.create')}?assignable_id=${props.choice.id}&assignable_type=choice` }
    ],
    [
        { name: 'Archive', as: 'emitter', icon: ArchiveBoxIcon, emit: 'open' }
    ]
];
</script>

<template>
    <Head :title="`Admin - Choices - ${choice.name}`" />

    <AdminLayout>
        <div class="w-full py-8 px-4 sm:px-6 lg:px-8">
            <div class="-ml-4 -mt-2 flex items-center justify-between flex-wrap sm:flex-nowrap">
                <div class="ml-4 mt-2">
                    <Header3> Choice Details: {{ choice.name }} </Header3>
                </div>
                <div class="ml-4">
                    <SecondaryButtonWithDropdown button-text="Options" :actions="actions" @open="open = true" />
                </div>
            </div>
            <div class="mt-4 bg-white shadow overflow-hidden sm:rounded-lg">
                <dl class="sm:divide-y sm:divide-gray-200">
                    <div class="py-4 sm:py-5 sm:grid sm:grid-cols-4 sm:gap-4 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500">Name</dt>
                        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-3"> {{ choice.name }} </dd>
                    </div>
                    <div class="py-4 sm:py-5 sm:grid sm:grid-cols-4 sm:gap-4 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500">Goal</dt>
                        <dd class="mt-1 text-sm font-bold text-gray-900 sm:mt-0 sm:col-span-3">
                            <Link class="hover:text-gray-600" :href="route('editor.goals.show', [choice.goal.id])"> {{ choice.goal.name }} </Link>
                        </dd>
                    </div>
                    <div class="py-4 sm:py-5 sm:grid sm:grid-cols-4 sm:gap-4 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500">Summary</dt>
                        <dd class="mt-1 prose text-sm text-gray-900 sm:mt-0 sm:col-span-3" v-html="choice.summary" />
                    </div>
                    <div class="py-4 sm:py-5 sm:grid sm:grid-cols-4 sm:gap-4 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500">Instructions</dt>
                        <dd class="mt-1 prose text-sm text-gray-900 sm:mt-0 sm:col-span-3" v-html="choice.instructions" />
                    </div>
                    <div v-if="choice.exercises" class="py-4 sm:py-5 sm:grid sm:grid-cols-4 sm:gap-4 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500">Resources</dt>
                        <dd class="mt-1 prose text-sm text-gray-900 sm:mt-0 sm:col-span-3" v-html="choice.resources" />
                    </div>
                    <div v-if="choice.review" class="py-4 sm:py-5 sm:grid sm:grid-cols-4 sm:gap-4 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500">Review</dt>
                        <dd class="mt-1 prose text-sm text-gray-900 sm:mt-0 sm:col-span-3" v-html="choice.review" />
                    </div>
                    <div v-if="choice.exercises" class="py-4 sm:py-5 sm:grid sm:grid-cols-4 sm:gap-4 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500">Exercises</dt>
                        <dd class="mt-1 prose text-sm text-gray-900 sm:mt-0 sm:col-span-3" v-html="choice.exercises" />
                    </div>
                </dl>
            </div>
        </div>

        <Teleport to="body">
            <DangerModal :open="open" action-text="Archive" emit-name="delete" @close="close" @delete="destroy">
                <DialogTitle as="h3" class="text-lg leading-6 font-medium text-gray-900"> Archive choice </DialogTitle>
                <div class="mt-2">
                    <p class="text-sm text-gray-500">Are you sure you want to archive {{ choice.name }}?</p>
                </div>
            </DangerModal>
        </Teleport>
    </AdminLayout>
</template>
