// resources/js/Components/Forms/AddCoverImage.vue
<script setup>
import { ref } from 'vue';
import BreezeInputError from '@/Components/InputError.vue';
import BreezeLabel from '@/Components/Label.vue';
import SecondaryButtonSmall from '@/Components/Buttons/SecondaryButtonSmall.vue';

defineProps(['image_path','image_url','message']);

const emit = defineEmits(['set']);

const photoPreview = ref(null);
const photoInput = ref(null);

const updatePhotoPreview = () => {
    const photo = photoInput.value.files[0];
    if (! photo) return;
    const reader = new FileReader();
    reader.onload = (e) => {
        photoPreview.value = e.target.result;
    };
    reader.readAsDataURL(photo);

    emit('set', photoInput.value.files[0]);
}
</script>

<template>
    <div class="px-6 sm:grid sm:grid-cols-5 sm:gap-4 sm:items-start sm:border-t sm:border-gray-200 sm:py-4">
        <BreezeLabel for="cover" value="Cover image" class="sm:mt-px sm:pt-1" />
        <div class="mt-1 sm:mt-0 sm:col-span-4">
            <input ref="photoInput" type="file" class="hidden" @change="updatePhotoPreview">
            <div v-show="! photoPreview && image_path">
                <img :src="image_url" class="block w-full h-72 rounded-lg bg-cover bg-no-repeat bg-center object-cover pointer-events-none">
            </div>
            <div v-show="photoPreview" class="mt-2">
                <span
                    class="block w-full h-72 rounded-lg bg-cover bg-no-repeat bg-center"
                    :style="'background-image: url(\'' + photoPreview + '\');'"
                />
            </div>
            <div :class="[image_path || photoPreview ? 'mt-3' : 'mt-0', 'space-x-4']">
                <SecondaryButtonSmall @click.prevent="$refs.photoInput.click()">
                    Select A New Cover Image
                </SecondaryButtonSmall>
            </div>
            <BreezeInputError class="mt-1" :message="message" />
        </div>
    </div>
</template>

// resources/js/Components/Forms/AddCoverImage.tsx
import {ChangeEvent, ReactElement, useRef, useState} from "react";
import InputLabel from "@/Components/Forms/InputLabel";
import classNames from "@/Utils/classNames";
import SecondaryButtonSmall from "@/Components/Buttons/SecondaryButtonSmall";
import InputError from "@/Components/Forms/InputError";

export default function ({
  errorMessage,
  imagePath,
  imageUrl,
  onChange,
  name,
}: {
  errorMessage: string | undefined;
  imagePath: string;
  imageUrl: string;
  onChange: (value: File) => void;
  name: string;
}): ReactElement {
  const [imagePreview, setImagePreview] = useState<string>();

  const handleImageChange = (e: ChangeEvent<HTMLInputElement>) => {
    const { files } = e.target;

    if (files) {
      setImagePreview(URL.createObjectURL(files[0]));
      onChange(files[0]);
    }
  };

  const localRef = useRef<HTMLInputElement>(null);

  return (
    <div className="px-6 sm:grid sm:grid-cols-8 sm:gap-4 sm:items-start sm:border-t sm:border-gray-200 sm:py-4">
      <InputLabel label="Cover Image" className="sm:mt-px sm:pt-1"/>
      <div className="mt-1 sm:mt-0 sm:col-span-7">
        <input
          type="file"
          accept="image/*"
          className="hidden"
          onChange={(e) => handleImageChange(e)}
          ref={localRef}
        />

        {imagePreview !== undefined && (
          <span
            className="block w-full h-72 rounded-lg bg-cover bg-no-repeat bg-center"
            style={{
              backgroundSize: 'cover',
              backgroundRepeat: 'no-repeat',
              backgroundPosition: 'center center',
              backgroundImage: `url('${imagePreview}')`,
            }}
          />
        )}
        {imagePath !== undefined && (
          <img
            src={imageUrl}
            alt={name}
            className="block w-full h-72 rounded-lg bg-cover bg-no-repeat bg-center object-cover pointer-events-none"
          />
        )}
        <div className={classNames(
          imagePath || imagePreview ? 'mt-3' : 'mt-0', 'space-x-4'
        )}>
          <SecondaryButtonSmall  onClick={() => localRef.current?.click()}>
            Select a new cover image
          </SecondaryButtonSmall>
        </div>
        <InputError message={errorMessage} className="mt-1"/>
      </div>
    </div>
  );
}
