// resources/js/Components/Forms/DeleteAccount.vue
<script setup>
import { inject, ref } from 'vue';
import { DialogTitle } from '@headlessui/vue';
import { router } from '@inertiajs/vue3';
import DangerButton from '@/Components/Buttons/DangerButton.vue';
import DangerModal from '@/Components/Modals/DangerModal.vue';
import Header3 from '@/Components/Headers/Header3.vue';

defineProps(['hasRoles']);

const user = inject('user');

const open = ref(false);
const close = () => {
    open.value = false;
}

const submit = () => {
    router.delete(route('settings.delete-account', [user.id]));
}
</script>

<template>
    <div class="space-y-6 sm:space-y-5">
        <div>
            <Header3>Delete Account</Header3>
        </div>
        <div class="pt-4 border-t border-gray-200">
            <div class="space-y-6 sm:space-y-5">
                <div v-if="hasRoles" class="space-y-2">
                    <p class="text-sm">Your account currently has a role in the CMS.</p>
                    <p class="text-sm">You must have the role removed before you can delete your account.</p>
                </div>
                <div class="sm:pt-2">
                    <DangerButton
                        @click="open = true"
                        :disabled="hasRoles"
                    >Delete account</DangerButton>
                </div>
            </div>
        </div>
    </div>

    <Teleport to="body">
        <DangerModal :open="open" action-text="Delete" emit-name="delete" @close="close" @delete="submit">
            <DialogTitle as="h3" class="text-lg leading-6 font-medium text-gray-900"> Delete account </DialogTitle>
            <div class="mt-2">
                <p class="text-sm text-gray-500">Are you sure you want to delete your account? All data will be permanently removed forever. This action cannot be undone.</p>
            </div>
        </DangerModal>
    </Teleport>
</template>

// resources/js/Components/Forms/DeleteAccount.tsx
import {FormEventHandler, useRef, useState} from "react";
import {router, useForm} from "@inertiajs/react";
import {Dialog} from "@headlessui/react";
import {Header3} from "@/Components/Typography/Headers";
import {Paragraph} from "@/Components/Typography/Paragraphs";
import DangerButton from "@/Components/Buttons/DangerButton";
import TextInput from "@/Components/Forms/TextInputCombined";
import DangerModal from "@/Components/Modals/Danger";
import {User} from "@/types";

export default function DeleteAccount({hasRoles, user}: { hasRoles: boolean, user: User }) {
  const [confirmingUserDeletion, setConfirmingUserDeletion] = useState(false)
  const passwordInput = useRef<HTMLInputElement>()

  const {
    data,
    setData,
    delete: destroy,
    processing,
    reset,
    errors
  } = useForm({
    password: ''
  })

  const confirmUserDeletion = (): void => {
    setConfirmingUserDeletion(true)
  }

  const deleteUser: FormEventHandler = (e) => {
    e.preventDefault()

    destroy(route('profile.destroy'), {
      preserveScroll: true,
      onSuccess: () => {
        closeModal()
      },
      onError: () => passwordInput.current?.focus(),
      onFinish: () => {
        reset()
      }
    })
  }

  const closeModal = (): void => {
    setConfirmingUserDeletion(false)

    reset()
  }

  return (
    <>
      <div className="space-y-6 sm:space-y-5">
        <div>
          <Header3>
            Delete Account
          </Header3>
        </div>
        <div className="pt-4 border-t border-gray-200">
          <div className="max-w-md space-y-6 sm:space-y-5">
            {hasRoles ? (
              <div className="space-y-2">
                <Paragraph>
                  Your account currently has a role in the CMS.
                </Paragraph>
                <Paragraph>
                  You must have the role removed before you can delete your account.
                </Paragraph>
              </div>
            ) : null}
            <DangerButton onClick={confirmUserDeletion} disabled={hasRoles}>
              Delete account
            </DangerButton>
          </div>
        </div>
      </div>

      <DangerModal maxWidthClass="sm:max-w-xl" destroy={deleteUser} open={confirmingUserDeletion} setOpen={setConfirmingUserDeletion}>
        <Dialog.Title as="h3" className="text-lg font-medium leading-6 text-gray-900">
          Are you sure you want to delete your account?
        </Dialog.Title>
        <div className="mt-2">
          <p className="text-sm text-gray-500">
            Once your account is deleted, all of its resources and data will be permanently deleted. Please
            enter your password to confirm you would like to permanently delete your account.
          </p>
        </div>
        <form className="mt-4">
          <TextInput
            label="Password"
            type="password"
            ref={passwordInput}
            value={data.password}
            onChange={(e) => { setData('password', e.target.value) }}
            className="block w-full"
            isFocused
            placeholder="Password"
            message={errors.password}
          />
        </form>
      </DangerModal>
    </>
  );
}
