// resources/js/Components/Forms/UpdateProfile.tsx
import { type FormEventHandler, type ReactElement } from 'react'
import { useForm } from '@inertiajs/react'
import { Header3 } from '@/Components/Typography/Headers'
import { Paragraph } from '@/Components/Typography/Paragraphs'
import TextInput from '@/Components/Forms/TextInput'
import PrimaryButton from '@/Components/Buttons/PrimaryButton'
import InputLabel from '@/Components/Forms/InputLabel'
import InputError from '@/Components/Forms/InputError'
import { type User } from '@/types'

export default function UpdateProfile ({ user }: { user: User }): ReactElement {
  const { data, setData, put, processing, errors, reset } = useForm({
    name: user.name,
    email: user.email
  })

  const updateProfile: FormEventHandler = (e): void => {
    e.preventDefault()

    put(route('settings.update-profile'), {
      preserveScroll: true,
      onSuccess: () => {
        reset()
      }
    })
  }

  return (
    <div className="space-y-6 sm:space-y-5">
      <div>
        <Header3>
          Public Profile
        </Header3>
        <Paragraph className="mt-1 max-w-2xl">
          This information will be displayed publicly so be careful what you share.
        </Paragraph>
      </div>
      <form onSubmit={updateProfile} className="pt-4 border-t border-gray-200">
        <div className="max-w-md space-y-6 sm:space-y-5">
          <div>
            <InputLabel label="Name"/>
            <TextInput
              value={data.name}
              className="mt-1 block w-full"
              isFocused={true}
              onChange={(e) => {
                setData('name', e.target.value)
              }}
              required
            />
            <InputError message={errors.name} className="mt-1"/>
          </div>

          <div>
            <InputLabel label="Email"/>
            <TextInput
              type="email"
              value={data.email}
              className="mt-1 block w-full"
              onChange={(e) => {
                setData('email', e.target.value)
              }}
              required
            />
            <InputError message={errors.email} className="mt-1"/>
          </div>

          <PrimaryButton disabled={processing}>
            Update profile
          </PrimaryButton>
        </div>
      </form>
    </div>
  )
}

// resources/js/Components/Forms/UpdateProfile.vue
<script setup>
import { inject } from 'vue';
import { useForm } from '@inertiajs/vue3';
import BreezeInput from '@/Components/Input.vue';
import BreezeInputError from '@/Components/InputError.vue';
import BreezeLabel from '@/Components/Label.vue';
import PrimaryButton from '@/Components/Buttons/PrimaryButton.vue';
import Header3 from '@/Components/Headers/Header3.vue';

const user = inject('user');

const form = useForm({
    ...user
});

const submit = () => {
    form.put(route('settings.update-profile', [user.id]));
}
</script>

<template>
    <div class="space-y-6 sm:space-y-5">
        <div>
            <Header3>Public Profile</Header3>
            <p class="mt-1 max-w-2xl text-sm text-gray-500">This information will be displayed publicly so be careful what you share.</p>
        </div>
        <form @submit.prevent="submit" class="pt-4 border-t border-gray-200">
            <div class="max-w-md space-y-6 sm:space-y-5">
                <div>
                    <BreezeLabel for="name" value="Name" />
                    <div class="mt-1">
                        <BreezeInput type="text" v-model="form.name" id="name" class="block w-full" />
                        <BreezeInputError class="mt-1" :message="form.errors?.name" />
                    </div>
                </div>
                <div>
                    <BreezeLabel for="email" value="Email" />
                    <div class="mt-1">
                        <BreezeInput type="email" v-model="form.email" id="name" class="block w-full" />
                        <BreezeInputError class="mt-1" :message="form.errors?.email" />
                    </div>
                </div>
                <div class="sm:pt-2">
                    <PrimaryButton>Update profile</PrimaryButton>
                </div>
            </div>
        </form>
    </div>
</template>
