// resources/js/Pages/Editor/Drafts/Create.tsx
import { type FormEventHandler, type ReactElement } from 'react'
import { Head, useForm } from '@inertiajs/react'
import Admin from '@/Layouts/Admin'
import Container from '@/Components/Container'
import { Header3 } from '@/Components/Typography/Headers'
import PrimaryButton from '@/Components/Buttons/PrimaryButton'
import AddCoverImage from '@/Components/Forms/AddCoverImage'
import TextEditor from '@/Components/Forms/TextEditor'
import InputLabel from '@/Components/Forms/InputLabel'
import TextInput from '@/Components/Forms/TextInput'
import InputError from '@/Components/Forms/InputError'
import ChoiceContentForm from '@/Components/Forms/Choices/ChoiceContentForm'
import { type PageProps } from '@/types'

export default function DraftCreate ({ auth, parentId, type }: PageProps<{ parent_id: number, type: string }>): ReactElement {
  const { data, setData, post, errors, processing } = useForm({
    type,
    parentId,
    name: '',
    image: {},
    summary: null,
    show_me_video_url: null,
    content: []
  })

  const updateCover = (value: File): void => {
    setData('image', value)
  }

  const submit: FormEventHandler = (e) => {
    e.preventDefault()
    if (typeof data.image !== 'object') {
      delete data.image
    }
    post(route('editor.drafts.store'))
  }

  return (
    <>
      <Head title="Create Draft"/>

      <Admin user={auth.user}>
        <Container>
          <div className="flex items-center justify-between flex-wrap sm:flex-nowrap">
            <Header3>
              Create Draft
            </Header3>
            <PrimaryButton onClick={submit} disabled={processing}>
              Save
            </PrimaryButton>
          </div>

          <div className="mt-4 bg-white rounded-md shadow">
            <form className="sm:divide-y sm:divide-gray-200">
              <div className="px-6 sm:grid sm:grid-cols-8 sm:gap-4 sm:items-start sm:py-4">
                <InputLabel label="Name" className="sm:mt-px sm:pt-2"/>
                <div className="mt-1 sm:mt-0 sm:col-span-7">
                  <TextInput
                    value={data.name}
                    className="block w-full"
                    isFocused={true}
                    onChange={(e) => {
                      setData('name', e.target.value)
                    }}
                  />
                  <InputError message={errors.name}/>
                </div>
              </div>

              {type === 'project' ? (
                <AddCoverImage
                  name={data.name}
                  errorMessage={errors.image}
                  imagePath={data?.cover_image_path}
                  imageUrl={data?.cover_image_url}
                  onChange={(value) => { updateCover(value) }}
                />
              ) : null}

              {type === 'goal' ? (
                <>
                  <div className="px-6 sm:grid sm:grid-cols-8 sm:gap-4 sm:items-start sm:py-4">
                    <InputLabel label="Summary" className="sm:mt-px sm:pt-2"/>
                    <div className="mt-1 sm:mt-0 sm:col-span-7">
                      <TextEditor
                        value={data.summary}
                        update={(value) => {
                          setData('summary', value)
                        }}
                      />
                      <InputError message={errors.summary}/>
                    </div>
                  </div>

                  <div className="px-6 sm:grid sm:grid-cols-8 sm:gap-4 sm:items-start sm:py-4">
                    <InputLabel label={'"Show Me" Video'} className="sm:mt-px sm:pt-2"/>
                    <div className="mt-1 sm:mt-0 sm:col-span-7">
                      <TextInput
                        value={data.show_me_video_url}
                        className="block w-full"
                        onChange={(e) => {
                          setData('show_me_video_url', e.target.value)
                        }}
                      />
                      <InputError message={errors.show_me_video_url}/>
                    </div>
                  </div>
                </>
              ) : null}

              {type === 'choice' ? (
                <ChoiceContentForm content={data.content}/>
              ) : null}
            </form>
          </div>
        </Container>
      </Admin>
    </>
  )
}

// resources/js/Pages/Editor/Content/Goals/Create.vue
<script setup>
import AdminLayout from '@/Layouts/Admin.vue';
import { Head, useForm } from '@inertiajs/vue3';
import BreezeInput from '@/Components/Input.vue';
import BreezeInputError from '@/Components/InputError.vue';
import BreezeLabel from '@/Components/Label.vue';
import TextEditor from '@/Components/TextEditor.vue';
import PrimaryButton from '@/Components/Buttons/PrimaryButton.vue';
import SecondaryButton from '@/Components/Buttons/SecondaryButton.vue';
import Header3 from '@/Components/Headers/Header3.vue';

const props = defineProps({
    project: Object,
});

const goal = useForm({
    name: '',
    project_id: props.project.id,
    summary: null,
    show_me_video_url: '',
});

const submit = () => {
    goal.post(route('editor.goals.store'));
}
</script>

<template>
    <Head title="Admin - Create Goal" />

    <AdminLayout>
        <div class="w-full py-8 px-4 sm:px-6 lg:px-8">
            <Header3> Create Goal </Header3>
            <div class="mt-4 bg-white rounded-md shadow">
                <form @submit.prevent="submit" class="space-y-6 divide-y divide-gray-200">
                    <div class="space-y-8 divide-y divide-gray-200 sm:space-y-5">
                        <div>
                            <div class="space-y-6 sm:space-y-5">
                                <div class="px-6 sm:grid sm:grid-cols-5 sm:gap-4 sm:items-start sm:pt-5">
                                    <BreezeLabel for="name" value="Goal name" class="sm:mt-px sm:pt-2" />
                                    <div class="mt-1 sm:mt-0 sm:col-span-4">
                                        <BreezeInput type="text" v-model="goal.name" id="name" class="block w-full" />
                                        <BreezeInputError class="mt-1" :message="goal.errors?.name" />
                                    </div>
                                </div>
                                <div class="px-6 sm:grid sm:grid-cols-5 sm:gap-4 sm:items-start sm:border-t sm:border-gray-200 sm:pt-5">
                                    <BreezeLabel for="name" value="Summary" class="sm:mt-px sm:pt-2" />
                                    <div class="mt-1 sm:mt-0 sm:col-span-4">
                                        <TextEditor v-model="goal.summary" />
                                        <BreezeInputError class="mt-1" :message="goal.errors?.summary" />
                                    </div>
                                </div>
                                <div class="px-6 sm:grid sm:grid-cols-5 sm:gap-4 sm:items-start sm:border-t sm:border-gray-200 sm:pt-5">
                                    <BreezeLabel for="name" value='"Show Me" video url' class="sm:mt-px sm:pt-2" />
                                    <div class="mt-1 sm:mt-0 sm:col-span-4">
                                        <BreezeInput type="text" v-model="goal.show_me_video_url" id="name" class="block w-full" />
                                        <BreezeInputError class="mt-1" :message="goal.errors?.show_me_video_url" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="px-6 py-4">
                        <div class="flex justify-end">
                            <SecondaryButton :href="route('editor.projects.show', [project.slug])" as="link">Cancel</SecondaryButton>
                            <PrimaryButton type="submit" class="ml-3">Save</PrimaryButton>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </AdminLayout>
</template>
