// resources/js/Pages/Editor/Content/Goals/Show.tsx
import { type FormEventHandler, type ReactElement, useState } from 'react'
import { Head, Link, router, useForm } from '@inertiajs/react'
import { Dialog } from '@headlessui/react'
import Admin from '@/Layouts/Admin'
import Container from '@/Components/Container'
import { Header3 } from '@/Components/Typography/Headers'
import SecondaryButtonWithDropdown from '@/Components/Buttons/SecondaryButtonWithDropdown'
import TableHeader from '@/Components/Tables/TableHeader'
import Table from '@/Components/Tables/Table'
import TableHead from '@/Components/Tables/TableHead'
import TableBody from '@/Components/Tables/TableBody'
import Prose from '@/Components/Prose'
import DangerModal from '@/Components/Modals/Danger'
import { type Choice, type Goal, type PageProps } from '@/types'
import ExpandableStackedListItem from '@/Components/Lists/ExpandableStackedListItem'

export default function GoalShow ({ auth, goal }: PageProps<{
  goal: Goal
}>): ReactElement {
  const [confirmGoalArchive, setConfirmGoalArchive] = useState(false)

  const updateOrder = (updated: Choice, sibling: Choice): void => {
    const { put } = useForm({
      updated,
      sibling
    })

    put(route('editor.choices.update-order'), {
      preserveScroll: true
    })
  }

  const archive: FormEventHandler = (e) => {
    e.preventDefault()

    router.delete(route('editor.goals.destroy', [goal.id]))
  }

  const sortedChoices = goal.choices.sort((a, b) => a.order - b.order)

  const findChoiceIndex = (orderNumber: number): number => {
    return sortedChoices.findIndex(choice => choice.order === orderNumber)
  }

  const moveDown = (orderNumber: number): void => {
    const index = findChoiceIndex(orderNumber)

    sortedChoices[index].order++
    sortedChoices[index + 1].order--

    updateOrder(sortedChoices[index + 1], sortedChoices[index])
  }

  const moveUp = (orderNumber: number): void => {
    const index = findChoiceIndex(orderNumber)

    sortedChoices[index].order--
    sortedChoices[index - 1].order++

    updateOrder(sortedChoices[index - 1], sortedChoices[index])
  }

  const actions = [
    [
      { name: 'Edit', as: 'link', icon: 'PencilSquareIcon', href: route('editor.goals.edit', [goal.id]) },
      { name: 'Add Assignment', as: 'link', icon: 'PlusCircleIcon', href: `${route('admin.assignments.create')}?assignable_id=${goal.id}&assignable_type=goal` },
      { name: 'Preview Goal', as: 'link', icon: 'WindowIcon', href: route('editor.goals.preview', [goal.id]), target: '_blank' }
    ],
    [
      { name: 'Archive', as: 'emitter', icon: 'ArchiveBoxIcon', emit: () => { setConfirmGoalArchive(true) } }
    ]
  ]

  const draftCells = {
    name: 'Name',
    user: 'Author',
    updated_at: 'Last Updated'
  }
  const tableActions = {
    view: true,
    edit: true
  }

  return (
    <>
      <Head title={`Admin - Goals - ${goal.name}`}/>

      <Admin user={auth.user}>
        <Container>
          <div className="-ml-4 -mt-2 flex items-center justify-between flex-wrap sm:flex-nowrap">
            <div className="ml-4 mt-2">
              <Header3>
                Goal Details {goal.name}
              </Header3>
            </div>
            <div className="ml-4">
              <SecondaryButtonWithDropdown
                buttonText="Options"
                actions={actions}
              />
            </div>
          </div>

          <div className="mt-4 bg-white shadow overflow-hidden sm:rounded-lg">
            <dl className="sm:divide-y sm:divide-gray-200">
              <div className="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                <dt className="text-sm font-medium text-gray-500">
                  Name
                </dt>
                <dd className="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                  {goal.name}
                </dd>
              </div>
              <div className="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                <dt className="text-sm font-medium text-gray-500">
                  Summary
                </dt>
                <dd className="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                  <Prose html={goal.summary}/>
                </dd>
              </div>
              <div className="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                <dt className="text-sm font-medium text-gray-500">
                  &apos;Show Me&apos; Video
                </dt>
                <dd className="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                  {goal.show_me_video_url}
                </dd>
              </div>
              <div className="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                <dt className="text-sm font-medium text-gray-500">
                  Belongs to
                </dt>
                <dd className="mt-1 text-sm font-bold text-gray-900 sm:mt-0 sm:col-span-2">
                  <Link className="hover:text-gray-600" href={route('editor.projects.show', [goal.project_id])}>
                    {goal.project.name}
                  </Link>
                </dd>
              </div>
            </dl>
          </div>

          <div className="mt-12">
            <TableHeader
              header="Choices"
              addText="Add choice"
              addRoute={route('editor.drafts.create', { type: 'choice', parent_id: goal.id })}
            />
            <ul className="mt-3 space-y-2">
              {sortedChoices.map((choice) => <ExpandableStackedListItem item={choice} key={choice.id}/>)}
            </ul>
          </div>

          {goal.child_drafts.length > 0 ? (
            <div className="mt-12">
              <TableHeader header="Choice Drafts"/>
              <Table className="mt-2">
                <TableHead cells={draftCells} actions={true}/>
                <TableBody
                  cells={draftCells}
                  rows={goal.child_drafts}
                  routeType="editor.drafts"
                  actions={tableActions}
                />
              </Table>
            </div>
          ) : null}
        </Container>
      </Admin>

      <DangerModal dangerButtonText="Archive" destroy={archive} open={confirmGoalArchive} setOpen={setConfirmGoalArchive}>
        <Dialog.Title as="h3" className="text-lg font-medium leading-6 text-gray-900">
          Archive Goal
        </Dialog.Title>
        <div className="mt-2">
          <p className="text-sm text-gray-500">
            Are you sure you want to archive {goal.name}?
          </p>
        </div>
      </DangerModal>
    </>
  )
}

// resources/js/Pages/Editor/Content/Goals/Show.vue
<script setup>
import { computed, onMounted, onUnmounted, ref } from 'vue';
import { DialogTitle } from '@headlessui/vue';
import { DocumentPlusIcon, EyeIcon, PencilSquareIcon, TrashIcon } from '@heroicons/vue/24/outline';
import { ArchiveBoxIcon, PencilSquareIcon as PencilSquareIconSolid, PlusCircleIcon, WindowIcon } from '@heroicons/vue/24/solid';
import { Head, Link, router, useForm } from '@inertiajs/vue3';
import { useChoicesStore } from '@/Stores/choices';
import AdminLayout from  '@/Layouts/Admin.vue';
import DangerModal from '@/Components/Modals/DangerModal.vue';
import PrimaryButton from '@/Components/Buttons/PrimaryButton.vue';
import SecondaryButton from '@/Components/Buttons/SecondaryButton.vue';
import TableHeader from '@/Components/Tables/TableHeader.vue';
import Table from '@/Components/Tables/Table.vue';
import TableHead from '@/Components/Tables/TableHead.vue';
import TableBody from '@/Components/Tables/TableBody.vue';
import SecondaryButtonWithDropdown from '@/Components/Buttons/SecondaryButtonWithDropdown.vue';
import StackedListWrapper from '@/Components/Lists/StackedListWrapper.vue';
import ExpandableStackedListItem from '@/Components/Lists/ExpandableStackedListItem.vue';
import Header3 from '@/Components/Headers/Header3.vue';

const props = defineProps({
    errors: Object,
    goal: Object,
});

let sortedChoices = computed(() => props.goal.choices.sort((a, b) => a.order - b.order));

const store = useChoicesStore();

onMounted(() => store.$patch({ choices: sortedChoices }));
onUnmounted(() => store.$reset());

const open = ref(false);

const close = () => {
    open.value = false;
}
const destroy = () => {
    router.delete(route('editor.goals.destroy', [props.goal.slug]));
}
const reload = () => {
    router.reload({ only: ['goal.choices'] });
}

const updateOrder = (updated_choice, sibling_choice) => {
    let updateForm = useForm({
        _method: "PUT",
        updated_choice,
        sibling_choice
    });

    updateForm.post(route('editor.choices.update-order', [updated_choice]), {
        preserveScroll: true,
    });
}

const moveDown = (orderNumber) => {
    let index = sortedChoices.value.findIndex(choice => choice.order === orderNumber);

    sortedChoices.value[index].order++;
    sortedChoices.value[index + 1].order--;

    updateOrder(sortedChoices.value[index + 1], sortedChoices.value[index]);
}
const moveUp = (orderNumber) => {
    let index = sortedChoices.value.findIndex(choice => choice.order === orderNumber);

    sortedChoices.value[index].order--;
    sortedChoices.value[index - 1].order++;

    updateOrder(sortedChoices.value[index - 1], sortedChoices.value[index]);
}

const actions = [
    [
        { name: 'Edit', as: 'link', icon: PencilSquareIconSolid, href: route('editor.goals.edit', [props.goal.slug]) },
        { name: 'Add Assignment', as: 'link', icon: PlusCircleIcon, href: `${route('admin.assignments.create')}?assignable_id=${props.goal.id}&assignable_type=goal` },
        { name: 'Preview Goal', as: 'link', icon: WindowIcon, href: route('editor.goals.preview', [props.goal.slug]), target: '_blank' }
    ],
    [
        { name: 'Archive', as: 'emitter', icon: ArchiveBoxIcon, emit: 'open' }
    ]
];
const draftCells = {
    name: 'Name',
    user: 'Author',
    updated_at: 'Last Updated'
}
const tableActions = {
    view: true,
    edit: true
}
</script>

<template>
    <Head :title="`Admin - Goals - ${goal.name}`" />

    <AdminLayout>
        <div class="w-full py-8 px-4 sm:px-6 lg:px-8">
            <div>
                <div class="-ml-4 -mt-2 flex items-center justify-between flex-wrap sm:flex-nowrap">
                    <div class="ml-4 mt-2">
                        <Header3> Goal Details: {{ goal.name }} </Header3>
                    </div>
                    <div class="ml-4">
                        <SecondaryButtonWithDropdown button-text="Options" :actions="actions" @open="open = true" />
                    </div>
                </div>
                <div class="mt-4 bg-white shadow overflow-hidden sm:rounded-lg">
                    <dl class="sm:divide-y sm:divide-gray-200">
                        <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                            <dt class="text-sm font-medium text-gray-500">Name</dt>
                            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"> {{ goal.name }} </dd>
                        </div>
                        <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                            <dt class="text-sm font-medium text-gray-500">Summary</dt>
                            <dd class="mt-1 prose max-w-3xl prose-a:text-blue-500 text-sm text-gray-900 sm:mt-0 sm:col-span-2" v-html="goal.summary" />
                        </div>
                        <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                            <dt class="text-sm font-medium text-gray-500">"Show Me" Video</dt>
                            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"> {{ goal.show_me_video_url }} </dd>
                        </div>
                        <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                            <dt class="text-sm font-medium text-gray-500">Project</dt>
                            <dd class="mt-1 text-sm font-bold text-gray-900 sm:mt-0 sm:col-span-2">
                                <Link class="hover:text-gray-600" :href="route('editor.projects.show', [goal.project.slug])"> {{ goal.project.name }} </Link>
                            </dd>
                        </div>
                    </dl>
                </div>
                <div class="mt-12">
                    <TableHeader header="Choices" addText="Add choice" :add-route="route('editor.drafts.create', {type: 'choice', parent_id: goal.id})" />

                    <StackedListWrapper class="mt-3">
                        <ExpandableStackedListItem v-for="choice in sortedChoices" :key="choice.id" :item="choice" @reload="reload" />
                    </StackedListWrapper>
                </div>

                <div class="mt-12" v-if="goal.child_drafts.length">
                    <TableHeader header="Goal Drafts" />
                    <Table class="mt-2">
                        <TableHead :cells="draftCells" :actions="true" />
                        <TableBody :cells="draftCells" :rows="goal.child_drafts" routeType="editor.drafts" :actions="tableActions" />
                    </Table>
                </div>
            </div>
        </div>

        <Teleport to="body">
            <DangerModal :open="open" action-text="Archive" emit-name="delete" @close="close" @delete="destroy">
                <DialogTitle as="h3" class="text-lg leading-6 font-medium text-gray-900"> Archive goal </DialogTitle>
                <div class="mt-2">
                    <p class="text-sm text-gray-500">Are you sure you want to archive {{ goal.name }}?</p>
                </div>
            </DangerModal>
        </Teleport>
    </AdminLayout>
</template>
