// resources/js/Pages/Admin/Editors/Accept.vue
<script setup>
import { Head, useForm } from '@inertiajs/vue3';
import BreezeGuestLayout from '@/Layouts/Guest.vue';
import PrimaryButtonFullWidth from '@/Components/Buttons/PrimaryButtonFullWidth.vue';
import BreezeInput from '@/Components/Input.vue';
import BreezeLabel from '@/Components/Label.vue';

const props = defineProps({
    invitation: Object,
    hasAccount: Boolean,
});

const registerForm = useForm({
    name: props.invitation.name,
    email: props.invitation.email,
    id: props.invitation.id,
    role: props.invitation.role,
    admin_id: props.invitation.admin_id,
    password: '',
    password_confirmation: '',
});

const acceptForm = useForm({
    email: props.invitation.email,
    role: props.invitation.role,
    admin_id: props.invitation.admin_id,
    id: props.invitation.id,
});

const submitRegister = () => {
    registerForm.post(route('invitations.register'), {
        onFinish: () => registerForm.reset('password', 'password_confirmation'),
    });
}

const submitAccept = () => {
    acceptForm.post(route('invitations.accept'));
}
</script>

<template>
    <BreezeGuestLayout>
        <Head title="Accept Invitation" />

        <div class="text-center sm:pt-1 sm:text-left">
            <p class="text-sm font-medium text-gray-500">Welcome,</p>
            <p class="text-xl font-bold text-gray-900 sm:text-2xl">{{ invitation.name }}</p>
        </div>
        <div class="mt-4">
            <template v-if="hasAccount">
                <p class="mt-1 text-sm text-gray-500">We see you already have an account for {{ invitation.email }}.</p>
                <div class="mt-8">
                    <PrimaryButtonFullWidth @click="submitAccept">Accept Invitation</PrimaryButtonFullWidth>
                </div>
            </template>
            <template v-else>
                <p class="mt-1 text-sm text-gray-500">Please complete your account by adding a password.</p>
                <form class="mt-3 mb-1" @submit.prevent="submitRegister">
                    <div>
                        <BreezeLabel for="name" value="Name" />
                        <BreezeInput id="name" type="text" class="mt-1 block w-full" v-model="registerForm.name" required autocomplete="name" />
                    </div>

                    <div class="mt-4">
                        <BreezeLabel for="email" value="Email" />
                        <BreezeInput id="email" type="email" class="mt-1 block w-full" v-model="registerForm.email" required autocomplete="username" />
                    </div>

                    <div class="mt-4">
                        <BreezeLabel for="password" value="Password" />
                        <BreezeInput id="password" type="password" class="mt-1 block w-full" v-model="registerForm.password" required autofocus autocomplete="new-password" />
                    </div>

                    <div class="mt-4">
                        <BreezeLabel for="password_confirmation" value="Confirm Password" />
                        <BreezeInput id="password_confirmation" type="password" class="mt-1 block w-full" v-model="registerForm.password_confirmation" required autocomplete="new-password" />
                    </div>

                    <div class="mt-8">
                        <PrimaryButtonFullWidth>Register & Accept Invitation</PrimaryButtonFullWidth>
                    </div>
                </form>
            </template>
        </div>
    </BreezeGuestLayout>
</template>

// resources/js/Pages/Admin/Editors/Accept.tsx
import {FormEventHandler, type ReactElement} from "react";
import {Head, useForm} from "@inertiajs/react";
import Guest from "@/Layouts/Guest";
import PrimaryButtonFullWidth from "@/Components/Buttons/PrimaryButtonFullWidth";
import TextInputCombined from "@/Components/Forms/TextInputCombined";
import TextInput from "@/Components/Forms/TextInputCombined";

export default function EditorAccept({ invitation, hasAccount }): ReactElement {
  const {
    post: postAccept,
    processing: processingAccept,
  } = useForm({
    email: invitation.email,
    role: invitation.role,
    admin_id: invitation.admin_id,
    id: invitation.id,
  });

  const submitAccept: FormEventHandler = (e) => {
    e.preventDefault();

    postAccept(route('invitations.accept'));
  }

  const {
    data,
    setData,
    reset,
    errors,
    post: postRegister,
    processing: processingRegister,
  } = useForm({
    name: invitation.name,
    email: invitation.email,
    id: invitation.id,
    role: invitation.role,
    admin_id: invitation.admin_id,
    password: '',
    password_confirmation: '',
  });

  const submitRegister: FormEventHandler = (e) => {
    e.preventDefault();

    postRegister(route('invitations.register'), {
      onFinish: () => reset('password', 'password_confirmation'),
    });
  }

  return (
    <>
      <Head title="Accept Invitation"/>

      <Guest>
        <div className="text-center sm:pt-1 sm:text-left">
          <p className="text-sm font-medium text-gray-500">
            Welcome,
          </p>
          <p className="text-xl font-bold text-gray-900 sm:text-2xl">
            {invitation.name}
          </p>
        </div>
        <div className="mt-4">
          {hasAccount ? (
            <>
              <p className="mt-1 text-sm text-gray-500">
                It looks like you already have an account for {invitation.email}.
              </p>
              <div className="mt-8">
                <PrimaryButtonFullWidth onClick={submitAccept} disabled={processingAccept}>
                  Accept Invitation
                </PrimaryButtonFullWidth>
              </div>
            </>
          ) : (
            <>
              <p className="mt-1 text-sm text-gray-500">
                Please complete your account by adding a password.
              </p>
              <form onSubmit={submitRegister} className="mt-3 mb-1 space-y-3">
                <TextInput
                  label="Name"
                  value={data.name}
                  className="mt-1 block w-full"
                  isFocused
                  message={errors.name}
                  onChange={(e) => {
                    setData('name', e.target.value)
                  }}
                  required
                />

                <TextInput
                  label="Email"
                  type="email"
                  value={data.email}
                  className="mt-1 block w-full"
                  message={errors.email}
                  onChange={(e) => {
                    setData('email', e.target.value)
                  }}
                  required
                />

                <TextInput
                  label="Password"
                  type="password"
                  value={data.password}
                  className="mt-1 block w-full"
                  onChange={(e) => {
                    setData('password', e.target.value)
                  }}
                  required
                />

                <TextInput
                  label="Confirm Password"
                  type="password"
                  value={data.password_confirmation}
                  className="mt-1 block w-full"
                  onChange={(e) => {
                    setData('password_confirmation', e.target.value)
                  }}
                  required
                />

                <div className="mt-8">
                  <PrimaryButtonFullWidth>
                    Register &amp; Accept Invitation
                  </PrimaryButtonFullWidth>
                </div>
              </form>
            </>
          )}
        </div>
      </Guest>
    </>
  );
}
