// resources/js/Pages/Admin/Editors/Show.vue
<script setup>
import { computed, ref } from 'vue';
import { DialogTitle } from '@headlessui/vue';
import { PencilSquareIcon, UserMinusIcon } from '@heroicons/vue/24/solid';
import { Head, useForm, usePage } from '@inertiajs/vue3';
import AdminLayout from '@/Layouts/Admin.vue';
import SecondaryButton from '@/Components/Buttons/SecondaryButton.vue';
import Badge from '@/Components/Badge.vue';
import SecondaryButtonWithDropdown from '@/Components/Buttons/SecondaryButtonWithDropdown.vue';
import DangerModal from '@/Components/Modals/DangerModal.vue';
import Header3 from '@/Components/Headers/Header3.vue';

const props = defineProps({
    user: Object,
});

const open = ref(false);

const close = () => {
    open.value = false;
}

const remove = () => {
    let form = useForm({
        _method: 'DELETE'
    });

    form.post(route('admin.editors.remove', props.user.id));
}

const usersMatch = usePage().props.auth.user.id === props.user.id;

const upperCaseRole = computed(() => props.user.roles[0].name.charAt(0).toUpperCase() + props.user.roles[0].name.slice(1));

const actions = [
    [
        { name: 'Edit', as: 'link', icon: PencilSquareIcon, href: route('admin.editors.edit', [props.user.id]) }
    ],
    [
        { name: `Remove ${upperCaseRole.value}`, as: 'emitter', icon: UserMinusIcon, emit: 'open', disabled: usersMatch }
    ]
];
</script>

<template>
    <Head :title="`Admin - ${user.name}`" />

    <AdminLayout>
        <div class="w-full py-8 px-4 sm:px-6 lg:px-8">
            <div>
                <div class="-ml-4 -mt-2 flex items-center justify-between flex-wrap sm:flex-nowrap">
                    <div class="ml-4 mt-2">
                        <Header3> Editor Details: {{ user.name }} </Header3>
                    </div>
                    <div class="ml-4 mt-2 space-x-2">
                        <SecondaryButtonWithDropdown button-text="Options" :actions="actions" @open="open = true" />
                    </div>
                </div>
                <div class="mt-4 bg-white shadow overflow-hidden sm:rounded-lg">
                    <dl class="sm:divide-y sm:divide-gray-200">
                        <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                            <dt class="text-sm font-medium text-gray-500">Name</dt>
                            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"> {{ user.name }} </dd>
                        </div>
                        <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                            <dt class="text-sm font-medium text-gray-500">Email</dt>
                            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"> {{ user.email }} </dd>
                        </div>
                        <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                            <dt class="text-sm font-medium text-gray-500">Role</dt>
                            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                                <Badge :text="user.roles[0].name" />
                            </dd>
                        </div>
                        <div v-if="user.admin" class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                            <dt class="text-sm font-medium text-gray-500">Admin</dt>
                            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"> {{ user.admin.name }} </dd>
                        </div>
                    </dl>
                </div>
            </div>
        </div>

        <Teleport to="body">
            <DangerModal :open="open" action-text="Remove" emit-name="remove" @close="close" @remove="remove">
                <DialogTitle as="h3" class="text-lg leading-6 font-medium text-gray-900"> Remove {{ user.roles[0].name }} </DialogTitle>
                <div class="mt-2">
                    <p class="text-sm text-gray-500">Are you sure you want to remove {{ user.name }}?</p>
                </div>
            </DangerModal>
        </Teleport>
    </AdminLayout>
</template>

// resources/js/Pages/Admin/Editors/Show.tsx
import { type ReactElement, useState } from 'react'
import { Head, router } from '@inertiajs/react'
import Admin from '@/Layouts/Admin'
import Container from '@/Components/Container'
import { Header3 } from '@/Components/Typography/Headers'
import SecondaryButtonWithDropdown from '@/Components/Buttons/SecondaryButtonWithDropdown'
import DescriptionListItem from '@/Components/Lists/DescriptionListItem'
import Badge from '@/Components/Badge'
import { type PageProps, type User } from '@/types'
import DangerModal from '@/Components/Modals/Danger'
import { Dialog } from '@headlessui/react'

export default function EditorShow ({ auth, user }: PageProps<{ user: User }>): ReactElement {
  const [confirmRemoveUserRole, setConfirmRemoveUserRole] = useState<boolean>(false)

  const removeRole = (): void => {
    router.post(route('admin.editors.remove', user.id))
  }

  const usersMatch = auth.user.id === user.id

  const upperCaseRole = (): string => user.roles[0].name.charAt(0).toUpperCase() + user.roles[0].name.slice(1)

  const actions = [
    [
      { name: 'Edit', as: 'link', icon: 'PencilSquareIcon', href: route('admin.editors.edit', [user.id]) }
    ],
    [
      { name: `Remove ${upperCaseRole()}`, as: 'emitter', icon: 'UserMinusIcon', emit: () => { setConfirmRemoveUserRole(true) }, disabled: usersMatch }
    ]
  ]

  return (
    <>
      <Head title={`Admin - ${user.name}`}/>

      <Admin user={auth.user}>
        <Container>
          <div className="-ml-4 -mt-2 flex items-center justify-between flex-wrap sm:flex-nowrap">
            <div className="ml-4 mt-2">
              <Header3>
                Editor Details: {user.name}
              </Header3>
            </div>
            <div className="ml-4">
              <SecondaryButtonWithDropdown
                buttonText="Options"
                actions={actions}
              />
            </div>
          </div>

          <div className="mt-4 bg-white shadow overflow-hidden sm:rounded-lg">
            <dl className="sm:divide-y sm:divide-gray-200">
              <DescriptionListItem term="Name" details={user.name}/>
              <DescriptionListItem term="Email" details={user.email}/>
              <DescriptionListItem term="Role" details={<Badge text={user.roles[0].name}/>}/>
              {user.admin !== null ? (
                <DescriptionListItem term="Admin" details={user.admin.name}/>
              ) : null}
            </dl>
          </div>
        </Container>
      </Admin>

      <DangerModal
        destroy={removeRole}
        open={confirmRemoveUserRole}
        setOpen={setConfirmRemoveUserRole}
        dangerButtonText="Remove"
      >
        <Dialog.Title as="h3" className="text-lg font-medium leading-6 text-gray-900">
          Remove Role
        </Dialog.Title>
        <div className="mt-2">
          <p className="text-sm text-gray-500">
            Are you sure you want to remove {user.name}&apos;s role?
          </p>
        </div>
      </DangerModal>
    </>
  )
}
