// resources/js/Pages/Editor/Content/Pages/Show.tsx
import {type ReactElement} from "react";
import {type Page, type PageProps} from "@/types";
import {Head} from "@inertiajs/react";
import Admin from "@/Layouts/Admin";
import Container from "@/Components/Container";
import {Header3} from "@/Components/Typography/Headers";
import SecondaryButtonWithDropdown from "@/Components/Buttons/SecondaryButtonWithDropdown";

type PageShowProps = {
  page: Page
} & PageProps

export default function PageShow ({ auth, page }: PageShowProps): ReactElement {
  const actions = [
    [
      { name: 'Edit', as: 'link', icon: 'PencilSquareIcon', href: route('editor.pages.edit', [page.id]) }
    ],
    [
      { name: 'Archive', as: 'emitter', icon: 'ArchiveBoxIcon', emit: () => {} }
    ]
  ]

  return (
    <>
      <Head title={`Admin - Pages - ${page.name}`}/>

      <Admin user={auth.user}>
        <Container>
          <div className="-ml-4 -mt-2 flex items-center justify-between flex-wrap sm:flex-nowrap">
            <div className="ml-4 mt-2">
              <Header3>
                Page Details: {page.name}
              </Header3>
            </div>
            <div className="ml-4">
              <SecondaryButtonWithDropdown
                actions={actions}
                buttonText="Options"
              />
            </div>
          </div>

          <div className="mt-4 bg-white shadow overflow-hidden sm:rounded-lg">
            <dl className="sm:divide-y sm:divide-gray-200">
              <div className="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                <dt className="text-sm font-medium text-gray-500">
                  Name
                </dt>
                <dd className="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                  {page.name}
                </dd>
              </div>
            </dl>
          </div>
        </Container>
      </Admin>
    </>
  )
}

// resources/js/Pages/Admin/Editors/Show.vue
<script setup>
import { PencilSquareIcon, UserMinusIcon } from '@heroicons/vue/24/solid';
import { Head } from '@inertiajs/inertia-vue3';
import AdminLayout from '@/Layouts/Admin';
import SecondaryButton from '@/Components/SecondaryButton';
import Badge from '@/Components/Badge.vue';
import SecondaryButtonWithDropdown from '@/Components/Buttons/SecondaryButtonWithDropdown.vue';

const props = defineProps({
    user: Object,
});

const actions = [
    [
        { name: 'Edit', as: 'link', icon: PencilSquareIcon, href: route('admin.editors.edit', [props.user.id]) }
    ],
    [
        { name: `Remove ${props.user.roles[0].name.charAt(0).toUpperCase() + props.user.roles[0].name.slice(1)}`, as: 'emitter', icon: UserMinusIcon, emit: 'open' }
    ]
];
</script>

<template>
    <Head :title="`Admin - ${user.name}`" />

    <AdminLayout>
        <div class="w-full py-8 px-4 sm:px-6 lg:px-8">
            <div>
                <div class="-ml-4 -mt-2 flex items-center justify-between flex-wrap sm:flex-nowrap">
                    <div class="ml-4 mt-2">
                        <h3 class="text-lg leading-6 font-medium text-gray-900"> Editor Details: {{ user.name }} </h3>
                    </div>
                    <div class="ml-4 mt-2 space-x-2">
                        <!-- <SecondaryButton :href="route('admin.editors.edit', [user.id])" as="link" title="Edit user">
                            <PencilSquareIcon class="h-5 w-5" aria-hidden="true" />
                            <span class="sr-only">Edit {{ user.name }}</span>
                        </SecondaryButton> -->
                        <SecondaryButtonWithDropdown button-text="Options" :actions="actions" @open="open = true" />
                    </div>
                </div>
                <div class="mt-4 bg-white shadow overflow-hidden sm:rounded-lg">
                    <dl class="sm:divide-y sm:divide-gray-200">
                        <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                            <dt class="text-sm font-medium text-gray-500">Name</dt>
                            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"> {{ user.name }} </dd>
                        </div>
                        <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                            <dt class="text-sm font-medium text-gray-500">Email</dt>
                            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"> {{ user.email }} </dd>
                        </div>
                        <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                            <dt class="text-sm font-medium text-gray-500">Role</dt>
                            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                                <Badge :text="user.roles[0].name" />
                            </dd>
                        </div>
                    </dl>
                </div>
            </div>
        </div>
    </AdminLayout>
</template>
