// resources/js/Pages/Auth/Login.tsx
import {Head, Link, useForm} from "@inertiajs/react";
import TextInput from "@/Components/Forms/TextInput";
import Checkbox from "@/Components/Forms/Checkbox";
import Guest from "@/Layouts/Guest";
import PrimaryButton from "@/Components/Buttons/PrimaryButton";

export default function Login({ status, canResetPassword }: {
  status?: string
  canResetPassword: boolean
}) {
  const { data, setData, post, processing, errors, reset } = useForm({
    email: '',
    password: '',
    remember: false
  });

  return (
    <Guest>
      <Head title="Login"/>

      {status !== null && <div className="mb-4 font-medium text-sm text-green-600">{status}</div>}

      <form className="space-y-4">
        <TextInput
          label="Email"
          type="email"
          value={data.email}
          className="mt-1 block w-full"
          isFocused={true}
          message={errors.email}
          onChange={(e) => {
            setData('email', e.target.value)
          }}
        />

        <TextInput
          label="Password"
          type="password"
          value={data.password}
          className="mt-1 block w-full"
          onChange={(e) => {
            setData('password', e.target.value)
          }}
        />

        <div className="block mt-4">
          <label className="flex items-center">
            <Checkbox
              name="remember"
              checked={data.remember}
              onChange={(e) => {
                  setData('remember', e.target.checked)
              }}
            />
            <span className="ml-2 text-sm text-gray-600">Remember me</span>
          </label>
        </div>

        <div className="mt-4 flex items-center justify-end">
            {canResetPassword && (
                <Link
                    href={route('password.request')}
                    className="underline text-sm text-gray-600 hover:text-gray-900 rounded-md focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
                >
                    Forgot your password?
                </Link>
            )}

            <PrimaryButton className="ml-4" disabled={processing}>
                Log in
            </PrimaryButton>
        </div>
      </form>
    </Guest>
  );
}

// resources/js/Pages/Auth/Login.vue
<script setup>
import BreezeButton from '@/Components/Button.vue';
import BreezeCheckbox from '@/Components/Checkbox.vue';
import BreezeGuestLayout from '@/Layouts/Guest.vue';
import BreezeInput from '@/Components/Input.vue';
import BreezeLabel from '@/Components/Label.vue';
import BreezeValidationErrors from '@/Components/ValidationErrors.vue';
import { Head, Link, useForm } from '@inertiajs/vue3';

defineProps({
    canResetPassword: Boolean,
    status: String,
});

const form = useForm({
    email: '',
    password: '',
    remember: false
});

const submit = () => {
    form.post(route('login'), {
        onFinish: () => form.reset('password'),
    });
};
</script>

<template>
    <BreezeGuestLayout>
        <Head title="Log in" />

        <BreezeValidationErrors class="mb-4" />

        <div v-if="status" class="mb-4 font-medium text-sm text-green-600">
            {{ status }}
        </div>

        <form @submit.prevent="submit">
            <div>
                <BreezeLabel for="email" value="Email" />
                <BreezeInput id="email" type="email" class="mt-1 block w-full" v-model="form.email" required autofocus autocomplete="username" />
            </div>

            <div class="mt-4">
                <BreezeLabel for="password" value="Password" />
                <BreezeInput id="password" type="password" class="mt-1 block w-full" v-model="form.password" required autocomplete="current-password" />
            </div>

            <div class="block mt-4">
                <label class="flex items-center">
                    <BreezeCheckbox name="remember" v-model:checked="form.remember" />
                    <span class="ml-2 text-sm text-gray-600">Remember me</span>
                </label>
            </div>

            <div class="flex items-center justify-end mt-4">
                <Link v-if="canResetPassword" :href="route('password.request')" class="underline text-sm text-gray-600 hover:text-gray-900">
                    Forgot your password?
                </Link>

                <BreezeButton class="ml-4" :class="{ 'opacity-25': form.processing }" :disabled="form.processing">
                    Log in
                </BreezeButton>
            </div>
        </form>
    </BreezeGuestLayout>
</template>
