// resources/js/Pages/Auth/Register.tsx
import { useEffect, type FormEventHandler, type ReactElement } from 'react';
import { Head, Link, useForm } from '@inertiajs/react';
import Guest from "@/Layouts/Guest";
import TextInput from "@/Components/Forms/TextInput";
import PrimaryButton from "@/Components/Buttons/PrimaryButton";

export default function Register () {
    const { data, setData, post, processing, errors, reset } = useForm({
        name: '',
        email: '',
        password: '',
        password_confirmation: ''
    });

    useEffect(() => {
        return () => {
            reset('password', 'password_confirmation')
        }
    }, []);

    const submit: FormEventHandler = (e) => {
        e.preventDefault()

        post(route('register'))
    };

    return (
        <Guest>
            <Head title="Register"/>

            <form className="space-y-4" onSubmit={submit}>
                <TextInput
                    label="Name"
                    value={data.name}
                    className="mt-1 block w-full"
                    isFocused={true}
                    message={errors.name}
                    onChange={(e) => {
                        setData('name', e.target.value)
                    }}
                    required
                />

                <TextInput
                    label="Email"
                    type="email"
                    value={data.email}
                    className="mt-1 block w-full"
                    message={errors.email}
                    onChange={(e) => {
                        setData('email', e.target.value)
                    }}
                    required
                />

                <TextInput
                    label="Password"
                    type="password"
                    value={data.password}
                    className="mt-1 block w-full"
                    onChange={(e) => {
                        setData('password', e.target.value)
                    }}
                    required
                />

                <TextInput
                    label="Confirm Password"
                    type="password"
                    value={data.password_confirmation}
                    className="mt-1 block w-full"
                    onChange={(e) => {
                        setData('password_confirmation', e.target.value)
                    }}
                    required
                />

                <div className="flex items-center justify-end mt-4">
                    <Link
                        href={route('login')}
                        className="underline text-sm text-gray-600 hover:text-gray-900 rounded-md focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
                    >
                        Already registered?
                    </Link>

                    <PrimaryButton className="ml-4" disabled={processing}>
                        Register
                    </PrimaryButton>
                </div>
            </form>
        </Guest>
    );
}

// resources/js/Pages/Auth/Register.vue
<script setup>
import BreezeButton from '@/Components/Button.vue';
import BreezeGuestLayout from '@/Layouts/Guest.vue';
import BreezeInput from '@/Components/Input.vue';
import BreezeLabel from '@/Components/Label.vue';
import BreezeValidationErrors from '@/Components/ValidationErrors.vue';
import { Head, Link, useForm } from '@inertiajs/vue3';

const form = useForm({
    name: '',
    email: '',
    password: '',
    password_confirmation: '',
    terms: false,
});

const submit = () => {
    form.post(route('register'), {
        onFinish: () => form.reset('password', 'password_confirmation'),
    });
};
</script>

<template>
    <BreezeGuestLayout>
        <Head title="Register" />

        <BreezeValidationErrors class="mb-4" />

        <form @submit.prevent="submit">
            <div>
                <BreezeLabel for="name" value="Name" />
                <BreezeInput id="name" type="text" class="mt-1 block w-full" v-model="form.name" required autofocus autocomplete="name" />
            </div>

            <div class="mt-4">
                <BreezeLabel for="email" value="Email" />
                <BreezeInput id="email" type="email" class="mt-1 block w-full" v-model="form.email" required autocomplete="username" />
            </div>

            <div class="mt-4">
                <BreezeLabel for="password" value="Password" />
                <BreezeInput id="password" type="password" class="mt-1 block w-full" v-model="form.password" required autocomplete="new-password" />
            </div>

            <div class="mt-4">
                <BreezeLabel for="password_confirmation" value="Confirm Password" />
                <BreezeInput id="password_confirmation" type="password" class="mt-1 block w-full" v-model="form.password_confirmation" required autocomplete="new-password" />
            </div>

            <div class="flex items-center justify-end mt-4">
                <Link :href="route('login')" class="underline text-sm text-gray-600 hover:text-gray-900">
                    Already registered?
                </Link>

                <BreezeButton class="ml-4" :class="{ 'opacity-25': form.processing }" :disabled="form.processing">
                    Register
                </BreezeButton>
            </div>
        </form>
    </BreezeGuestLayout>
</template>
